### ISSUE TITLE
Update readme file and implement Graphql query options

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#193]
Like:

```things(schema: "givenName:John") {```

```things(schema: "givenName:Joh%") {```

@johnciocoiu how it is documented in the Readme file will be the guide to implementation.

**Comment by johnciocoiu** [comment]
There is no option in Dgraph to search with wild cards. What you can do is search with `eq` (==) `anyoftext` (any of the provided text separated with spaces) or `alloftext` (all of the provided text separated with spaces). 

**My suggestion:**

_Search with `eq` when:_
```things(schema: "givenName:John") {```

_Search with `anyoftext` when:_
```things(schema: "givenName:~John") {```

**Comment by bobvanluijt** [comment]
Cool, agreed!

**Comment by johnciocoiu** [comment]
Add more operators to README for searching on _inequalities_:

This one will be implemented in this issue:

Search with `not equal` when:
```things(schema: "givenName!=John") {```

The following will be implemented in another issue issue: https://github.com/weaviate/weaviate/issues/202

Search with `less than` when:
```things(schema: "givenName<John") {```

Search with 'less than or equal' when:
```things(schema: "givenName<=John") {```

Search with `greater than` when:
```things(schema: "givenName>John") {```

Search with 'greater than or equal' when:
```things(schema: "givenName>=John") {```

**Comment by johnciocoiu** [comment]
Dgraph seems to have a bug:

Doing the following query **doesn't** respond any data:
```{
        keys(func: eq(uuid, "37f42c98-3aca-48d9-812f-19b875711b20")) {
            things: ~key @filter(eq(_type_, "Thing")  AND alloftext(schema.givenName, "patc")) (orderdesc: creationTimeUnix, first: 1, offset: 0)  {
                expand(_all_) {
                    expand(_all_)
                }
            }
        }
    }
```

Doing the following query **do** respond data:
```{
        keys(func: eq(uuid, "37f42c98-3aca-48d9-812f-19b875711b20")) {
            things: ~key @filter(eq(_type_, "Thing")  AND alloftext(schema.givenName, "patch")) (orderdesc: creationTimeUnix, first: 1, offset: 0)  {
                expand(_all_) {
                    expand(_all_)
                }
            }
        }
    }
```
_The only difference is 'patc' and 'patch' as search text_

But, when searching with _alloftext_, every `thing` has to be found with a `givenName` that contains the given string.

The `thing`'s `givenName` is `New name patched!`, so:

1. The thing should be found when using `patc` as search term
2. The thing should be found when using `patch` as search term
3. The thing should be found when using `patched` as search term

Case 1 fails, case 2 and 3 succeed.

**Comment by johnciocoiu** [comment]
Drop issue on Dgraph github.

**Comment by johnciocoiu** [comment]
https://github.com/dgraph-io/dgraph/issues/1632

**Comment by johnciocoiu** [comment]
Change the working from full text search to regex.

**Comment by johnciocoiu** [comment]
Possible to search on 'class':

Search with `equal` when:
```listThings(class:"Person") {```

Search with `contains` when:
```listThings(class:"~erso") {```

Search with `not equal` when:
```listThings(class:"!:Person") {```

Searching with `~` only possible with AT LEAST 3 characters.
