### ISSUE TITLE
Key should be deleted with parent key (cannot remove itself)

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#195]
A key cannot remove itself, only parents.

- [x] @johnciocoiu implement
- [ ] @bobvanluijt write in Readme.

**Comment by bobvanluijt** [comment]
Note: Also fix in swagger.

**Comment by johnciocoiu** [comment]
@bobvanluijt Fixed in swagger, a release can be made.

**Comment by johnciocoiu** [comment]
I've done the release in swagger already.
