### ISSUE TITLE
Weaviate on Docker is not running

### ISSUE THREAD

**Issue by johnciocoiu** [creativesoftwarefdn/weaviate#205]
After running the following command, everything seems to be working:

`curl https://raw.githubusercontent.com/weaviate/weaviate/develop/docker/run-services.sh -sSf | bash`

But, this error keeps popping up:

`Retrying req: 1. Error: rpc error: code = Unavailable desc = grpc: the connection is unavailable`

This means that Weaviate is running, but Dgraph isn't. Weaviate is stuck on initializing Dgraph. Can you check if it is working or not?

**Comment by bobvanluijt** [comment]
Note to self: Do a better job in the future

**Comment by johnciocoiu** [comment]
@bobvanluijt Hint: use 0.0.0.0 as `--host` when starting the Weaviate server. This will allow external connection.
