### ISSUE TITLE
GraphQL: do not return property value 'null' if property is not in weaviate instance

### ISSUE THREAD

**Issue by laura-ham** [creativesoftwarefdn/weaviate#250]
do not return null as value, but do not return the property value at all

**Comment by johnciocoiu** [comment]
Can't reproduce this. Or I don't understand the bug. @laura-ham, can you explain it? Just for the record: it is not possible to return something else than 'null' if the user requests for a field that is not filled in for a certain object (thing/action).

**Comment by laura-ham** [comment]
@johnciocoiu Exactly as you explain. Since it is not possible to return anything else than 'null' if the user requests for a field that is empty, this issue is no longer an issue.
