### ISSUE TITLE
Actions: change properties of object or not?

### ISSUE THREAD

**Issue by laura-ham** [creativesoftwarefdn/weaviate#271]
To think about: 
When an action happens, the state of an object may change. This is not included in the action now, but should this be included? This can be important when asking the status of Things in a query (so you just have to query the Thing instead of last actions about that thing).

**Comment by johnciocoiu** [comment]
Implement

**Comment by johnciocoiu** [comment]
It is now also possible to update (PUT) the Action. But what Laura states here is that the status of a `Thing` could be influenced by an action. For example: When a light is going from state 'on' to state 'off', the Thing's /schema/status value should be changed. I think this is the resposibility for the Thing itself, knowing what actions are taken on it, to change its own status. What do you think, Bob?
