### ISSUE TITLE
git clone takes to much time, repo size is big

### ISSUE THREAD

**Issue by e7dal** [creativesoftwarefdn/weaviate#282]
the total repo size after initial clone is 1.4G

find a better way to distribute the binaries, and keep the repo size small, use this repo just for source files

**Comment by e7dal** [comment]
https://help.github.com/articles/distributing-large-binaries/ github recommends to use releases.
https://help.github.com/articles/about-releases/
https://help.github.com/articles/creating-releases

i will try this at some point in  https://github.com/e7dal/weaviate

and then the released binary files should be removed out of the repo and history
something like this:
https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository#2158271

**Comment by e7dal** [comment]
repo size is still very big.
the removed old binaries are as far as i can tell still in commit history.

maybe try some of the solutions provided here:
https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository#2158271

**Comment by bobvanluijt** [comment]
This has to do with a /bin directory somewhere hidden in de git-tree.

Do you mind taking that up @e7dal? Maybe create a new issue for this.

**Comment by moretea** [comment]
If we are indeed going to do this, we need to sync on this up front with
everyone that is working on a feature branch.

This requires rewriting the repository from the moment this was added; and
will invalidate all feature branches.

Op vr 24 aug. 2018 om 13:52 schreef Bob van Luijt <notifications@github.com

**Comment by bobvanluijt** [comment]
Ok, so we need to plan around this when feature branches are done and can be closed. No prio for now.
