### ISSUE TITLE
Revert to go-swagger 0.12.0

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#298]
There is an issue with `schema/schema_handler.go` because the Models are changed _or_ the way the schema is defined.

`schema/schema_handler.go` should be fixed in `feature/feature/go-swagger-0.13.0` branch.

**Comment by johnciocoiu** [comment]
@bobvanluijt Could you use `go-swagger v0.12.0` as we discussed, because I couldn't get it working on `go-swagger v0.13.0`. It does not generate everything it supposed to create.
