### ISSUE TITLE
Renew key with PUT command

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#306]
A key should be renewed with a PUT.

**Comment by johnciocoiu** [comment]
@bobvanluijt 

*Review the swagger file*

The current operationId in swagger is `weaviate.keys.me.get.renew` which results in a function `KeysWeaviateKeysMeGetRenewHandler`. That is not what it does. I suggest to remove `/renew` from the URL and just a `PUT`-method is added to `/keys/me` _and_ `/keys/{keyId}`. See how it is done with the `DELETE`-method for `/keys/{keyId}`.
