### ISSUE TITLE
Explain Weaviate concepts

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#358]
In particular
* What is a thing?
* What is an action?
* What is a key?

**Comment by bobvanluijt** [comment]
Moved to: https://github.com/SeMI-network/semi-website/issues/71

Docs will be available on SeMI website.

**Comment by moretea** [comment]
Reopening, as discussed by telephone today.

**Comment by bobvanluijt** [comment]
Closing for it will be addressed in the vision doc directory.

**Comment by moretea** [comment]
@bobvanluijt are we tracking that somewhere?
