### ISSUE TITLE
Kinds must be selected from pre-definded ontology

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#359]
The value of Kinds is that they are from a common ontology. If they are free form, they provide no additional value compared to using just a class name.

We should perform some analysis on real-life datasets and expected queries, to determine which kinds are useful to have.

Examples that come to mind are:
* `GeoLocation`
* `Person`
* `Organization`
* `Transaction`
* `Product`
* `Price`

**Comment by bobvanluijt** [comment]
I disagree, they should be part of the vector to create a centroid. The kinds are the figure points to find the centroid of. _Unless_ there is another use-case for the kinds that I'm unaware of.

Ref: https://github.com/creativesoftwarefdn/weaviate#example-1

**Comment by moretea** [comment]
Per our last discussion, this feature should be renamed to `keywords`

**Comment by moretea** [comment]
New issue for keywords: #363
