### ISSUE TITLE
Add support for vectors and relate ontology

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#361]
- [ ] Import k-nn index (based on https://github.com/spotify/annoy)
- [ ] Add efficient `mmaped` wordlist --> (annoy index) index
- [ ] On startup, create in-memory Annoy index for the Ontologies.
- [ ] It should be possible to find the closest neighbor of a class (which class is closest to "City"?).
- [ ] Classify words with [wordnet](https://wordnet.princeton.edu/download/current-version), store in wordlist

**Comment by moretea** [comment]
@bobvanluijt can this be closed?

**Comment by bobvanluijt** [comment]
Yes @moretea :-)
