### ISSUE TITLE
Add CORS settings

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#367]
- [x] add CORS
- [ ] add CORS option to config file

**Comment by dljcollette** [comment]
Connecting Weaviate to the Playground gives me the following error: ```Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

Could we add CORS URL whitelisting or a wildcard?

**Comment by bobvanluijt** [comment]
They should be set but might have been removed. I’ll reopen this one.

@JeroenStravers1 can you help @dljcollette with this please? 
https://github.com/go-swagger/go-swagger/issues/481

**Comment by etiennedi** [comment]
By the way, I just verified, the `Access-Control-Allow-Origin` headers are missing on all requests, not just graphql. 

*(I used the key/token that can be found in the `docker-compose.yml` - since they aren't secret I've left them in my copy/paste)*

Maybe this middleware doesn't do what we think we do. From what I remember there are two things related to CORS

1. The allow origin headers (as are missing here)
2. Preflight requests (i.e. responding to a `HEAD` first) if "non-standard" headers are set. But the definition of what a standard-header is was quite strict, i.e. `Authorization` is already considered non standard.

Maybe the middleware only takes care of point 2, but not point 1?

### GraphQL Example
```sh
curl -v -X POST -H "Content-Type:application/json" \
  -d '{"query": ""}' \
  -H 'X-API-KEY: 657a48b9-e000-4d9a-b51d-69a0b621c1b9' \
  -H 'X-API-TOKEN: 57ac8392-1ecc-4e17-9350-c9c866ac832b' \
  localhost:8080/weaviate/v1/graphql
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /weaviate/v1/graphql HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type:application/json
> X-API-KEY: 657a48b9-e000-4d9a-b51d-69a0b621c1b9
> X-API-TOKEN: 57ac8392-1ecc-4e17-9350-c9c866ac832b
> Content-Length: 13
>
* upload completely sent off: 13 out of 13 bytes
< HTTP/1.1 422 Unprocessable Entity
< Content-Type: application/json
< Vary: Origin
< Date: Mon, 31 Dec 2018 10:41:38 GMT
< Content-Length: 15
<
{"error":null}
```

### REST API example
```sh
curl -v \
  -H 'X-API-KEY: 657a48b9-e000-4d9a-b51d-69a0b621c1b9' \
  -H 'X-API-TOKEN: 57ac8392-1ecc-4e17-9350-c9c866ac832b' \
  localhost:8080/weaviate/v1/things
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /weaviate/v1/things HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> X-API-KEY: 657a48b9-e000-4d9a-b51d-69a0b621c1b9
> X-API-TOKEN: 57ac8392-1ecc-4e17-9350-c9c866ac832b
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Vary: Origin
< Date: Mon, 31 Dec 2018 10:42:13 GMT
< Transfer-Encoding: chunked
<
# body removed to make it more readable
```

**Comment by etiennedi** [comment]
## Update: Figured it out

The CORS middleware only sends CORS headers if an origin header is present. If I include one it works fine (see example below). So just make sure you always include the origin on your request:

```sh
curl -v -X POST -H "Content-Type:application/json" \
  -d '{"query": ""}' \
  -H 'X-API-KEY: 657a48b9-e000-4d9a-b51d-69a0b621c1b9' \
  -H 'X-API-TOKEN: 57ac8392-1ecc-4e17-9350-c9c866ac832b' \
  -H 'Origin: some-origin.com' \ # <---------------------------------
  localhost:8080/weaviate/v1/graphql
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /weaviate/v1/graphql HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type:application/json
> X-API-KEY: 657a48b9-e000-4d9a-b51d-69a0b621c1b9
> X-API-TOKEN: 57ac8392-1ecc-4e17-9350-c9c866ac832b
> Origin: some-origin.com
> Content-Length: 13
>
* upload completely sent off: 13 out of 13 bytes
< HTTP/1.1 422 Unprocessable Entity
< Access-Control-Allow-Origin: * # <------------------------------------
< Content-Type: application/json
< Vary: Origin
< Date: Mon, 31 Dec 2018 10:53:51 GMT
< Content-Length: 15
<
{"error":null}
* Connection #0 to host localhost left intact
```

**Comment by bobvanluijt** [comment]
Aha, that was unexpected.

Can you please add this as a documentation issue for me @etiennedi?

**Comment by bobvanluijt** [comment]
Can you work with this @dljcollette?

**Comment by dljcollette** [comment]
> Can you work with this @dljcollette?

Sure, I'll add the origin to the GraphQL client. Thanks guys!
