### ISSUE TITLE
Fetch Contextionary based on an URL

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#382]
Extends #380.

Instead of specifying just the exact location of the Contextionary files, we should be able to specify four URL's, for the KNN and word index, and their hashes.

**Comment by bobvanluijt** [comment]
Is this still open @moretea?

**Comment by moretea** [comment]
It is not implemented at this moment.

**Comment by bobvanluijt** [comment]
Thx, in that case we'll keep it open.

**Comment by bobvanluijt** [comment]
Solved here: https://github.com/creativesoftwarefdn/weaviate/issues/595
