### ISSUE TITLE
Implement LocalFetch Graphql in Weaviate

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#384]
The GraphQL endpoint for Weaviate are designed and prototyped in this repository: https://github.com/bobvanluijt/weaviate-graphql-prototype

On the highest level, the GraphQL functionality looks like this:

```graphql
{
  Local{} # <== this is the focus of the issue
  Network{}
}
``` 

The `localFetch{}` contains 3 main functionalities;

```graphql
{
  Local{
    ConvertedFetch{}
    HelpersFetch{}
    MetaFetch{}
  }
}
```

All these three (including the sub-functions) need to be implemented as [described in the prototype](https://github.com/bobvanluijt/weaviate-graphql-prototype).

You can run [GraphiQL](https://github.com/graphql/graphiql) to explore the graphql setup. Running is described [here](https://github.com/bobvanluijt/weaviate-graphql-prototype#run-prototype).

<h1>End Point Handling</h1>

The Graphql endpoint itself is already implemented [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/restapi/configure_weaviate.go#L1205) the new endpoints can be constructed on top of this.

<h1>Query batching</h1>

Based on batching as described in [Apollo specs](https://www.apollographql.com/docs/link/links/batch-http.html).

From the description: _[...] automatically batch multiple queries into one request when they are made within a certain interval. This means that if you render several components, for example a navbar, sidebar, and content, and each of those do their own GraphQL query, they will all be sent in one roundtrip._

<h1>Todo</h1>

- [ ] ~~Implement [Facebook's dataloader](https://github.com/graph-gophers/dataloader) [[ref](https://github.com/facebook/dataloader)] in [operations/graphql](https://github.com/creativesoftwarefdn/weaviate/tree/develop/restapi/operations/graphql)~~
- [ ] implement query batching
- [x] Implement `Local{}`
- [x] Implement Local `ConvertedFetch{}`
- [x] Implement Local `HelpersFetch{}`
- [x] Implement Local `MetaFetch{}`
- [x] Implement Filters.
- [x] Pass tests

**Comment by moretea** [comment]
To help Jeroen get started, I updated the basic GraphQL endpoint structure, see https://github.com/creativesoftwarefdn/weaviate/commit/e02aeb8ff06edbae506784396a69a108dd00a1a9 during a pair programming session over video chat.

It contains the basic root query, a simple object, and shows how to loop through the `SemanticModel -> ActionSchema -> Schema -> Classes`. Explained over the video chat how this can be extended to properties in the model.

This also removes the token / key from the global GraphQL struct (_very_ unsafe!!! that's a data race!) and pushes it in the context that is threaded through the Resolvers.

**Comment by bobvanluijt** [comment]
@JeroenStravers1 please move this to a new issue to avoid it getting bloated.
