### ISSUE TITLE
In-memory backend

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#400]
A simple in-memory backend, usefull for testing.

**Comment by bobvanluijt** [comment]
Is this still open / relevant @moretea ?

**Comment by moretea** [comment]
I think so for local development/testing, but you asked me to move to the JanusGraph connector at the time, so no progress on this.

You also were thinking at this time about this being a potential enabler to put Weaviate on a smaller IoT like device.

**Comment by bobvanluijt** [comment]
Check, putting it on-hold for now. #Close
