### ISSUE TITLE
Repair security issue in GraphQL endpoint

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#410]
Yesterday, when I went through the GraphQL endpoints with Jeroen, I noticed that some assumptions were made in the implementation that are very unsafe.

The `net/http` server starts a new Go routine for every new request. If we have multiple requests that arrive at the same time, they can be run at the same time.

[Here](https://github.com/creativesoftwarefdn/weaviate/blob/c695aeaba3300fe616b336ec1179eeb8e215bc0d/restapi/configure_weaviate.go#L1245) we set a global variable to pass along the security identity to the GraphQL endpoint. This opens up the security issue that halfway through the resolving process of an GraphQL query, this identity could be updated and point to another user.

A better design would be to put the credentials in the context [here](https://github.com/creativesoftwarefdn/weaviate/blob/c695aeaba3300fe616b336ec1179eeb8e215bc0d/restapi/configure_weaviate.go#L1254).

**Comment by bobvanluijt** [comment]
Is this changed in the meantime @JeroenStravers1 ?

**Comment by moretea** [comment]
I fixed this yes.

**Comment by bobvanluijt** [comment]
Awesome @moretea
