### ISSUE TITLE
Review thread-safety of weaviate & prevent data races

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#411]
Go servers typically use Go routines to support handling concurrent requests. This requires that the implementer of the service is careful to prevent [data races](https://en.wikipedia.org/wiki/Race_condition#Software), which can have [security implications](https://en.wikipedia.org/wiki/Race_condition#Computer_security).

Given that there is a problem with thread-safety in #410, we probably should review the usage of the other global variables for concurrent access that might bite us when we deploy it.

**Comment by bobvanluijt** [comment]
Is this still relevant @moretea?

**Comment by moretea** [comment]
Yes.

Although the situation is better than before, there are probably still some glaring issues.

**Comment by bobvanluijt** [comment]
Check, thanks. Temporarily assigning to self.

**Comment by etiennedi** [comment]
Closing this as we have gradually removed global variables and implemented more and more locking. I'm not aware of any bad offenders, so I don't see a need for a blanket issue anymore. Once we identify potential races anywhere else, we can open specific issues for them.
