### ISSUE TITLE
Enable indexing in JanusGraph

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#414]
Extend the `Init()` function of the JanusGraph connector from #408 to perform indexing.

**Comment by bobvanluijt** [comment]
Is this one still relevant @moretea ?

**Comment by moretea** [comment]
There is no indexing yet, so if you want to have indexing, I'd suggest to keep this issue open yes.

**Comment by bobvanluijt** [comment]
Can you elaborate a bit more on this @moretea? Are we talking graph indexes _and_ vertex-centric indexes? Because I assume they are needed to solve certain use cases in the GraphQL endpoint, right?

**Comment by etiennedi** [comment]
Closing as we use Elasticsearch for some and Cassandra for other indices. Indexing can of course always be improved, but I believe this can be tracked in a new issue once we run into actual problems with the current indexing stratgies which seem fine for most cases at scale.
