### ISSUE TITLE
Make Contextionary optional

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#416]
The Contextionary is now required; Weaviate cannot start without it.

We could a similar trick like I did with the [network](https://github.com/creativesoftwarefdn/weaviate/blob/bf59370f6ea76f383d8bdc38669976a81369f4ec/config/config_handler.go#L52), so that we can check if the user has specified a contextionary or not.

If none was provided, an empty implementation that returns no results will be used.

Why? Then Weaviate can still be used for other purposes than the semantic network

**Comment by etiennedi** [comment]
@bobvanluijt Is this still relevant? Are there any cases where we'd want to run weaviate without a contextionary?

**Comment by bobvanluijt** [comment]
Nope, outdated.
