### ISSUE TITLE
How to deal with schema validation after a restart?

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#420]
Currently, a restart of Weaviate doesn't validate the ontologies. Which might screw up indexing etcetera,

- What can we do to validate the ontologies?
- Should a change fail, warn or okay?

**Comment by moretea** [comment]
Given that we have a schema, and validate it, it makes sense to do what other systems that have these properties do too.

Which is to store the schema _inside_ the database and offer a way to manipulate the schema. We could still use the existing schema as we have it now as a way to store the _initial_ schema.

**Comment by bobvanluijt** [comment]
We should decide if we want to define the schema externally or not. Now it is external through the JSON files. We could internalize this through a REST endpoint for this specific case. For example as part of the `/meta` endpoint.
