### ISSUE TITLE
Resolve GraphQL's local fetch to GetLocalGraph() in JanusGraph

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#426]
Every `graphql.Field.Resolve` within a `Local{}` GraphQL function should resolve to `Resolve: dbConnector.GetLocalGraph(ctx context.Context, p graphql.ResolveParams)` an example of this function can be found [here](https://github.com/creativesoftwarefdn/weaviate/blob/feature/janusgraph/connectors/foobar/connector.go#L92) or [here](https://github.com/creativesoftwarefdn/weaviate/blob/feature/janusgraph/connectors/foobar/connector.go#L92).

The `GetLocalGraph()` function _only_ resolves the `Local{}` GraphQL function. The GraphQL `Network{}` function will resolves elsewhere.

## Why?

Because all GraphQL requests (id est `graphql.ResolveParams`) are similar, different connectors should be able to handle the request.

## JanusGraph and other connectors

- Other connectors can -for now- return the basic `return nil, fmt.Errorf("Not supported for this connector")` error.
- An equivalent example of a resolver function can be found [here](https://github.com/bobvanluijt/weaviate-graphql-prototype/blob/master/server_small.js#L560). Sending an `interface{}` that contains the right JSON-like formatting (as in, key-value structures) will be handled by GraphQl directly.

## Examples

For example, old:

```Go
singleActionClassPropertyFieldsField := &graphql.Field{
	Type:        singleActionClassPropertyFieldsObj,
	Description: class.Description,
	Resolve: func(p graphql.ResolveParams) (interface{}, error) {
		return nil, fmt.Errorf("Not supported")
	},
}
```

For example, new:

```Go
singleActionClassPropertyFieldsField := &graphql.Field{
	Type:        singleActionClassPropertyFieldsObj,
	Description: class.Description,
	Resolve: dbConnector.GetLocalGraph(ctx context.Context, p graphql.ResolveParams),
}
```

# Misc

- In the past, this function was referred to as: `GetGraph()`
- Helper functions that go for all connectors can be added to the [utils](https://github.com/creativesoftwarefdn/weaviate/tree/feature/janusgraph/connectors/utils) directory.
- Although [most Fields](https://github.com/JeroenStravers1/weaviate/tree/feature/graphql/graphqlapi) currently contains a resolver function, it should be investigated if all are needed.

**Comment by bobvanluijt** [comment]
As for commit: https://github.com/creativesoftwarefdn/weaviate/commit/7e65baa2f8884198e49276728bffafec8b0e57a6

As an example I've added:

```go
Resolve: func(p graphql.ResolveParams) (interface{}, error) {
	result, err := dbConnector.GetGraph(p)
	return result, err
},
```

Obviously, this is just a mockup but it clearly shows how the function is related to the connectors.

**Comment by bobvanluijt** [comment]
cc: @JeroenStravers1   ⬆️

**Comment by etiennedi** [comment]
@bobvanluijt @JeroenStravers1 happy to help out on this over the weekend. If you're interested let me know, so we can align who does what and don't do the same work twice ;)

**Comment by bobvanluijt** [comment]
@etiennedi I think this one is from before my email, isn't it? ;-)

**Comment by etiennedi** [comment]
@bobvanluijt Indeed. Jereon was nice enough to schedule a meeting with me for tomorrow noon - so I should be all set up and ready to go.

**Comment by bobvanluijt** [comment]
Awesome!

**Comment by etiennedi** [comment]
FYI @bobvanluijt your commit 7e65baa broke the dev setup, see #488 (already has a PR to fix it)

CC @JeroenStravers1 since I've already emailed you about this ;)

**Comment by moretea** [comment]
This is slightly more complicated than suggested in https://github.com/creativesoftwarefdn/weaviate/issues/426#issuecomment-423550531.

It involves extracting the structure of the sub query at a certain level, translating that into Gremlin, resolving that, and then generating a result.

Closing in favor of #561 #562 #563.
