### ISSUE TITLE
Simplify authentication.

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#428]
If you're using an API token, it does not make it more secure to add an API key.

Dropping the token will make authentication simpler; the client generated by go-swagger does _not_ support setting two tokens.

Alternatively, we could switch to also supporting HTTP basic authentication, where by default you'd have an username and password, which can be translated to a key and token.

**Comment by bobvanluijt** [comment]
Closing because this will be handled in a separate issue and release.
