### ISSUE TITLE
Run local http server in tests

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#430]
Using [`http/httpest`](https://golang.org/pkg/net/http/httptest/#Server)will allow us to start a Weaviate server that listens to a random local port.
This can then hooked into a standard HTTP client to test the server.

If we add some minimal configuring functions to `restapi/*.go`, we should be able to test starting weaviate with different schema's, contextionaries, etc.

Furthermore, this should make the development cycle a bit easier; no need to run two programs in sequence, just run the tests.

Related: #412, #390, #400, #407

**Comment by bobvanluijt** [comment]
Obsolete
