### ISSUE TITLE
Add option to specify initial root key & token

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#432]
Currently, we need to browse the log output to extract the root key & token.

For the in-memory connector, I already implemented an option to be able to specify the root key & token upfront, which can make (manual) testing a bit more friendly to use.

**Comment by bobvanluijt** [comment]
@moretea great, thanks

**Comment by bobvanluijt** [comment]
@moretea can I assume from the commits that this is resolved? If so, is it documented or where can I find the needed information?

**Comment by etiennedi** [comment]
Obsolete as Key auth has been removed/replaced.
