### ISSUE TITLE
godownloader install script

### ISSUE THREAD

**Issue by e7dal** [creativesoftwarefdn/weaviate#435]
at the moment goreleaser is used like:
https://github.com/creativesoftwarefdn/weaviate/blob/develop/.travis.yml#L57

should we also use?
https://github.com/goreleaser/godownloader
godownloader - Download Go binaries as fast and easily as possible.

so we can  tell your our users to use: https://raw.githubusercontent.com/YOU/YOURAPP/master/godownloader.sh to install
and the install command something like: "curl .... | sh"

todo:
 - fix issue C++ , only compiles on compile architecture:
 - update goreleaser
 -possibly use: https://hub.docker.com/r/goreleaser/goreleaser/ (local/travis)

The c++ build issue is with:
https://github.com/creativesoftwarefdn/weaviate/blob/develop/contextionary/annoyindex/annoygomodule_wrap.cxx

This contextionary/annoy is a custom build for Weaviate en probably Gannoy has same issue.

https://go-search.org/view?id=github.com%2fmonochromegane%2fgannoy

replace goreleaser with goreleaser install with c++

**Comment by moretea** [comment]
For simplicity's sake I'd argue that we'd only support _one_ distribution format. A Docker image.

This would also open up the possibilities to build everything in a tightly controlled environment, that can also be used for development. See for example [this small project](https://hub.docker.com/r/moretea/docker-fetchurl/~/dockerfile/) I did in the weekend.

How goreleaser fits in this story should be investigated.

Keeping in mind that we would like to offer "market place" solutions hosted on the big clouds to our customers, only offering a Dockerfile perfectly reasonable too; we probably want to deploy Weaviate on top of a hosted Kubernetes cluster in any case.

**Comment by bobvanluijt** [comment]
Yes, I agree.

We actually use Goreleaser and only support [Linux](https://github.com/creativesoftwarefdn/weaviate/blob/develop/.goreleaser.yml) as an OS which works perfectly well with the proposed Docker setup.

What might be nice is to not use the cloud to store the binaries, but [Github releases](https://github.com/creativesoftwarefdn/weaviate/releases) instead.

PS:
Nice => [docker-fetchurl](https://hub.docker.com/r/moretea/docker-fetchurl/~/dockerfile/)

**Comment by e7dal** [comment]
yes, i also agree, with simplicity. and building and releasing just one linux image should be enough.
And if we have a bare docker image with just the released binary.

But i also still would love to see elegant solution for running in a bare metal/vm: "curl .... | sh" 
and it seems a simple thing to do, just adding the repo to godownloader.

does using github releases increase the repo size?
see also https://github.com/creativesoftwarefdn/weaviate/issues/282

**Comment by bobvanluijt** [comment]
Closing for changed relevance.
