### ISSUE TITLE
Test Kubernetes deployment in Travis

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#442]
A colleague of mine at CS shared [a blog about running minikube on Travis](https://blog.travis-ci.com/2017-10-26-running-kubernetes-on-travis-ci-with-minikube).

Based on the content, I'd say that this is a feasible strategy to test the future deployment manifests for Weaviate.

**Comment by bobvanluijt** [comment]
Fascinating, and yes, I agree.

**Comment by moretea** [comment]
Another resource here; [using docker-in-docker to do the same](https://github.com/kubernetes-sigs/kubeadm-dind-cluster).

**Comment by bobvanluijt** [comment]
Closing, starting a new thread with @idcrosby attached.
