### ISSUE TITLE
Store descriptive text strings in a central location

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#446]
Currently all String descriptors that a user will encounter are declared and instantiated where they are required in the code. This makes it more difficult to update them and increases the risk that we miss a few Strings when doing such an update. 

I suggest to store all Strings that a user will encounter in a central location/file. This will allow us to edit them with significantly less scroll-work and without fear of missing a few lines. It will also make it easier to implement a consistent writing style and to detect typos.

**Comment by moretea** [comment]
This feels pretty similar to using translation files. This can work fine, but we can be tricky. For the GraphQL instance that you're probably referring, I imagine that we _could_ have a separate `descriptions.go` file containing all const strings. The question is if this would make the readability and maintainability of the Go code better or worse?

If a string is repeated  multiple times throughout the code base (e.g. `Cannot resolve this property; not found in database`), then it should definitely be stored into a const variable.

But what if there is only one occurrence? Such as would be the case of a GraphQL Object description?
I would _not_ store this in a const variable in another file. If it makes your definition of the object/fields more clear, you can always write something like the snippet below.
This will keep the variable scoped to the function (making clear that it is only used for this function), and documents the doSomething function at the same time.

```go
package main

type SomeObject struct {
	Description string
}

func doSomething() *SomeObject {
	const description string = "Some Very Long" +
		"text" +
		"description"

	return &SomeObject{
		Description: description,
	}
}

func main() {
	_ = doSomething()
}
```
https://play.golang.org/p/prMA0CtyIpn

**Comment by JeroenStravers1** [comment]
Some descriptions were updated too in the recent schema update, implementing these changes would've been quicker if these strings were stored in a single location. This also goes for updating descriptions as a result of the acceptance test. @laura-ham is now updating the strings in the prototype that have already been updated in this repo, this would be easier if we were using a single location too.

These are the descriptions and names that users encounter, which means that of all strings used in the code these are most likely to be changed in the future (due to either user feedback or re-design). It's likely that these strings will have to be revisited multiple times in the future (over a large period of course, not weekly). They are currently spread out over four files, I think using a central location for them would make our life easier in the future (at specific (update) moments only, admittedly).

**Comment by JeroenStravers1** [comment]
implemented, merged with develop
