### ISSUE TITLE
Don't hardcode the list of supported database backends in the restapi.

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#449]

**Comment by bobvanluijt** [comment]
Not sure what you mean with this.

**Comment by moretea** [comment]
Closed by 39711778c5c71b4bb726f8748e605a33a6fca3ad

**Comment by moretea** [comment]
The point here is that you don't want the REST API to know about which connectors there are. This should be in the connector part of the code base.

It's a simple separation of concerns.

**Comment by bobvanluijt** [comment]
Yes, the API (assuming you include GQL in here) should be agnostic of the connectors.
