### ISSUE TITLE
Document/reevaluate history of Actions/Things

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#455]
- Is this still in line with the current vision?
- If not, can we not simply drop this?
- If so, how is this exposed in GraphQL

**Comment by bobvanluijt** [comment]
Closing for it will be addressed in the vision doc directory.

**Comment by moretea** [comment]
@bobvanluijt where is this being tracked now :)?

**Comment by bobvanluijt** [comment]
https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/overall_tech_vision.md which -I know 😬- needs quite the rework, it will also contain new ideas related to the above.
