### ISSUE TITLE
Make creating things/actions synchronous by default.

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#458]
Currently, we return a 202 (accepted), and spawn a goroutine to take care of persisting the change to the backend.
This can be very confusing for consumers as a default behavior.

We'll also add an async option, that will trigger the current behaviour

- [x] Add `async` flag in the swagger API, make default to add synchronized.
- [x] Extend swagger API documentation to explain the two options

**Comment by bobvanluijt** [comment]
I can add this to the API docs @moretea.
