### ISSUE TITLE
Store schema in the backend, have schema modification operations

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#459]
- [ ] Persist schema in backend
- [ ] Load initial schema from JSON/YAML file
- [ ] Add API endpoints to modify schema
- [ ] Add RW lock for all requests that can havesomething to do with the schema

**Comment by bobvanluijt** [comment]
Is still relevant @moretea?

**Comment by etiennedi** [comment]
Has been implemented quite some time ago.
