### ISSUE TITLE
Deployment to Kubernetes

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#460]
Write basic manifest to deploy Weaviate and it's required dependencies on a Kubernetes cluster.
- [ ] Manifest for 
- [ ] Investigate operator for Elasticsearch (probably [this one](https://github.com/upmc-enterprises/elasticsearch-operator))
- [ ] Investigate what to use for Cassandra, it's apprently a bit hard to run under k8s. Check out this [resource](https://github.com/instaclustr/cassandra-operator).

**Comment by bobvanluijt** [comment]
Already being covered by @idcrosby
