### ISSUE TITLE
Move documentation about Weaviate to this repository

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#463]
Move all documentation about Weaviate to this repository.
This enables us to release versioned documentation on the SeMI website, but make contributing to the documentation when a feature is finished simple.

**Comment by bobvanluijt** [comment]
Easiest is a `/docs` folder I guess.

**Comment by bobvanluijt** [comment]
Branch to use = https://github.com/creativesoftwarefdn/weaviate/tree/technical_design_document

**Comment by bobvanluijt** [comment]
Being picked up in more recent issues.
