### ISSUE TITLE
Make schema work in a HA setup

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#477]
With the changes that are going to happen in #468, we need a way to synchronize between multiple weaviate processes that form one "instance".

![image](https://user-images.githubusercontent.com/99988/45305344-5daa0200-b51a-11e8-8fcc-fad184954ce5.png)

**Comment by bobvanluijt** [comment]
Hi @moretea, what is the status of this issue (also based on our email conversation).

**Comment by moretea** [comment]
Implementing this would entail implementing two interfaces:

- https://github.com/creativesoftwarefdn/weaviate/blob/develop/database/manager.go
- https://github.com/creativesoftwarefdn/weaviate/blob/develop/database/locks.go#L8-L14

Simply follow the logic that instantiates the LocalSchemaManager from [here on](https://github.com/creativesoftwarefdn/weaviate/blob/develop/restapi/configure_weaviate.go#L1491-L1504).

**Comment by bobvanluijt** [comment]
Thanks @moretea!

**Comment by etiennedi** [comment]
Has been implemented by switching the schema management to etcd.
