### ISSUE TITLE
Fully implement dataloader and move it from connectors

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#480]
A previous attempt to implement a [dataloader](https://github.com/graph-gophers/dataloader) existed in the connectors folder until recently. Now that graphql-go's [#389](https://github.com/graphql-go/graphql/issues/389) has been resolved it can be fully implemented. The location of these functions in the existing codebase will have to be reevaluated.

**Comment by JeroenStravers1** [comment]
### Background
The dataloader exists as middleware between the GQL endpoint and the connectors. It implements the [BaseConnector](https://github.com/creativesoftwarefdn/weaviate/blob/03f6de48426e228c3e62337dd01d758a38ce7dc0/connectors/database_connector.go#L30) interface and behaves like a connector. The resolvers in the GQL endpoint point to the dataloader's [GetGraph()](https://github.com/creativesoftwarefdn/weaviate/blob/2ac5c0e260b06cc4896fc2a9f214317c36f5a0b5/connectors/utils/dataloader/graph.go#L8) (as per [#426](https://github.com/creativesoftwarefdn/weaviate/issues/480)), incoming traffic is mapped to the dataloader's specific functions (e.g. [GetActions()](https://github.com/creativesoftwarefdn/weaviate/blob/2ac5c0e260b06cc4896fc2a9f214317c36f5a0b5/connectors/utils/dataloader/actions.go#L47)). These functions currently point to the corresponding functions in the actual database connector (i.e. the JanusGraph connector's functions, essentially ignoring its `GetGraph()` function).

### Questions
* Should the dataloader's specific functions point to the connector's matching specific functions? 
* Should they point to the connector's `GetGraph()`?
* Any insights in this matter?

cc: @moretea @bobvanluijt

**Comment by bobvanluijt** [comment]
cc: @etiennedi

**Comment by bobvanluijt** [comment]
I think for questions 1 and 2 the answer should be yes _for now_. As soon as `GetGraph()` gets implemented this will most likely change. But I believe it is better if @JeroenStravers1 points to `GetGraph()` and the implementor (@moretea or @etiennedi) makes those changes.

**Comment by JeroenStravers1** [comment]
@etiennedi I just talked to Bob about this, he suggests the first option (which I agree with). What do you think?

**Comment by etiennedi** [comment]
I agree, based on your drawing - you showed me in the call - we would save quite some complexity. Nevertheless I'll assume the `GetGraph()` setup, similar to how @bobvanluijt described it in https://github.com/creativesoftwarefdn/weaviate/issues/426#issuecomment-423550531 for now - just to get started quickly. It should be easy to move whatever `GetGraph()` -> specific functions logic I'll end up with out of there in the future.

**Comment by etiennedi** [comment]
I withdraw my statement from before that I will use the `GetGraph()` method for now, now that I've understand how we use the dbConnector a bit better.

For example to list things in the RestAPI we simple call 
```
dbConnector.ListThings( /* plenty of params to control the query */ )
```

I don't see why why should do it any differently for GraphQL, so I'd propose something like
```
dbConnector.GraphqlListThings( params request graphql.ResolveParams )
```

In fact, I'm just building a minimal prototype for exactly that. Once I have something working we could use that as a proposal for the Graphql-related methods on the dbConnector interface.

This will mean the interface gets much bigger, but since it already has plenty of methods for the REST API, I don't think it would bother me if we had exactly the same for GraphQL as well?

**Comment by JeroenStravers1** [comment]
Based on @moretea's https://github.com/creativesoftwarefdn/weaviate/issues/494#issuecomment-424076021 option C can be discarded. Whether we implement option A or B does not impede implementing the dataloader, it would be a matter of changing the dataloader's function calls to the database connector.

**Comment by JeroenStravers1** [comment]
Closing this and related issues after learning we're implementing batching of our database requests in another manner.
