### ISSUE TITLE
Determining correct settings for batch wait and maxSize parameters

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#481]
## Description

I am working on implementing a [dataloader](https://github.com/graph-gophers/dataloader) in Weaviate so we can use batching and caching of requests. A dataloader uses wait and maxSize parameters to determine the interval between and capacity of batch requests, and I am trying to determine what values to use. 

## Details

An example of these values can be found in the now removed [legacy dataloader connector](https://github.com/creativesoftwarefdn/weaviate/blob/5db24c512ce23ba609f22fd8bcf127b349bcdae0/connectors/dataloader/connector.go) where we set;

- `await` at [50 milliseconds](https://github.com/creativesoftwarefdn/weaviate/blob/5db24c512ce23ba609f22fd8bcf127b349bcdae0/connectors/dataloader/connector.go#L202), and;
- `maxSize` at [100 requests](https://github.com/creativesoftwarefdn/weaviate/blob/5db24c512ce23ba609f22fd8bcf127b349bcdae0/connectors/dataloader/connector.go#L203).

## Question

- Are these parameter settings correct for use in Weaviate?
- Any other insights to determine these?

**Comment by bobvanluijt** [comment]
cc: @johnciocoiu you have any reason behind these values?

**Comment by johnciocoiu** [comment]
As discussed with Jeroen this morning, I have chosen them randomly or they
are just defaults.

Op wo 19 sep. 2018 09:42 schreef Bob van Luijt <notifications@github.com>:

**Comment by JeroenStravers1** [comment]
closing this issue as we decided to implement dataloader functionality in another way
