### ISSUE TITLE
Keep connector folder for connectors

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#485]
Currently, there are folders in the connector folder that are not connectors.

1. listing
2. utils

Utils is the exception to the rule because they are -well- utils for the connectors.

**Comment by bobvanluijt** [comment]
@moretea can we move listings into the utils folder?

**Comment by moretea** [comment]
Sure.

**Comment by bobvanluijt** [comment]
Cool, thanks

**Comment by bobvanluijt** [comment]
Related to: https://github.com/creativesoftwarefdn/weaviate/issues/597
