### ISSUE TITLE
Dev Setup requires more memory than docker's defaults

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#487]
When trying to run `docker-compose -f docker-compose-dev.yml up` with the default docker settings (at least on OS X), the elasticseach container will exit with status code 137 after a while, then leading to the entire docker-compose setup to crumble.

By default the local docker settings (at least on OS X) limit the docker memory usage to 2GB. As a quick fix I've increased the limits to 8 GB on my machine.

I think the high usage is fine considering how much we're spinning up, but we should mention the requirements  in the `docker-compose-dev.yml` similar to how we're explaining that a non-clean shutdown can lead to issues.

Any numbers on what the ideal setup is? I only know that 2GB is too little...

**Comment by moretea** [comment]
Ah, great! That might be the problem that I encountered before when trying to run Janus on a mac laptop for Christian to be able to use an actual Weaviate instance.

Could you try this out with lower settings (e.g. 4GB), and see if it still works? A PR for this would be awesome. It would allow Dominique to consume Weaviate itself pretty easily later on.

**Comment by bobvanluijt** [comment]
cc: @dljcollette ⬆️

**Comment by etiennedi** [comment]
I ran some tests as part of #534 

Since the only action item on here is to document the right numbers, I think this duplicates #534 and recommend closing this issue in favor of the other one.
