### ISSUE TITLE
Graphiql incompatible with current auth scheme

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#490]
When trying to develop end2end, as is required in connecting the GraphQL setup and the JanusGraph Setup (#426) we need to be able to run the docker-compose setup, so we have all the backends, but also need to query the GraphQL API.

This is considerable easier with a browser-client, such as GraphiQL. However, the current auth scheme requires us to set two Headers (`X-API-KEY` and `X-API-TOKEN`). Unfortunately GraphiQL does not support custom headers. (Compare: https://github.com/graphql/graphiql/issues/500). In this thread is also a recommendation for an alternative tool to replace GraphiQL: https://github.com/imolorhe/altair

@JeroenStravers1 suggested to simply turn off auth while developing by adding `return &models.KeyTokenGetResponse{}, nil` to the top of `headerAPIKeyHandling()` in `restapi/configure_weaviate.go`. This does work when running weaviate without a backend, but breaks the importer in our current docker-compose setup, because the importer gets 403 errors. So, we need a more permanent solution. 

In the meantime we can of course query GraphQL without any browser-frontend like so

```sh
echo curl -H "content-type: application/json" \
  -H "x-api-key: 657a48b9-e000-4d9a-b51d-69a0b621c1b9" \
  -H "x-api-token: 57ac8392-1ecc-4e17-9350-c9c866ac832b" \
  -d @grapqhl_query.json \
```
whereas the query file (`graphql_query.json`) looks something like:  
```
{
  "query": "{\n  Local {\n    Get {\n      Things {\n        City {\n          name\n        }\n      }\n    }\n  }\n}\n"
}
```

But that's not nearly as nice as developing with a proper GraphQL frontend like GraphiQL.

## Possible Actions:
- Add Feature Flag to turn off all auth during development (i.e. allowed to do everything without check for any tokens)
- Replace GraphiQL with Altair, as it supports setting custom headers
- Consider pursuing a TDD approach where we script all GraphQL interaction in tests and develop against them, so there is never a need to use a UI -> this makes it impossible to demo the GraphQL interface, though.

CC @moretea @bobvanluijt

**Comment by etiennedi** [comment]
/close

Just checked out the code that spins up `GraphiQL` and found that that's what the Basic Auth setup is for. 

For someone running into the same issue in the future:

```
Basic Auth Username <- API_KEY, see docker-compose-dev.yml
Basic Auth Password <- API_TOKEN, see docker-compose-dev.yml
```

No further action required now.

**Comment by etiennedi** [comment]
Is there anything like an FAQ for devs? We should consider adding on (maybe link it in the contribution guidelines). I'll keep documenting all the issues I run into onboarding, maybe we can streamline the process for the next person to be onboarded. ;)

**Comment by bobvanluijt** [comment]
Hi @etiennedi, you can find it here: https://github.com/creativesoftwarefdn/weaviate/tree/develop/docs

In due time usage information will be placed on our website.

**Comment by moretea** [comment]
Note that I actually added a simple middleware that does HTTP basic auth ([see this file](https://github.com/creativesoftwarefdn/weaviate/blob/develop/graphqlapi/graphiql/graphiql.go)).

The key / token should be passed in the HTTP basic auth, and bubble through the code until they are templated [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/graphqlapi/graphiql/graphiql.go#L167-L168). Then GraphiQL will send the correct headers to Weaviate.
