### ISSUE TITLE
Determining GQL endpoint resolver functions

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#494]
## Background
@etiennedi suggests linking GQL endpoint resolvers directly to functions in the database connector (dataloader) instead of to `GetGraph()` in his [PR](https://github.com/creativesoftwarefdn/weaviate/pull/491). I agree that this is the way forward, but am wondering about which functions these resolvers need to implement. If I understand this correctly we'd require:
* A get Things function (as in @etiennedi's PR)
* A get Actions function

## Questions
* Do we need other types of resolver functions in the GQL endpoint?
* Any other insights in this matter?

related: [#480](https://github.com/creativesoftwarefdn/weaviate/issues/480), [#426](https://github.com/creativesoftwarefdn/weaviate/issues/426)

cc: @laura-ham @bobvanluijt @etiennedi @moretea @e7dal

**Comment by bobvanluijt** [comment]
Why not relate it to the core functions GQL has?

That would _not_ be `getThings()` or `getActions()` but;
- `getLocalGet()`
- `getLocalMeta()`
- `getNetworkGet()`
- `getNetworkFetch()`
- `getNetworkIntrospect()`
Nomenclature would be: `[action] [Location] [function]` (e.g.; getLocalMeta)

You van add the type to the functions like:
- `getLocalGet('actions', p graphql.ResolveParams)`
- `getNetworkFetch('things', p graphql.ResolveParams)`
- `getNetworkIntrospect('beacon', p graphql.ResolveParams)`

Reference for ⬆️== [GQL network](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/graphql_network.md#query-structure) and [GQL local](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/graphql_local.md#query-structure) _Query Structure_ docs by @laura-ham.

**Comment by JeroenStravers1** [comment]
This seems like a good solution. After giving it some thought I do think we'd need specific functions for things and actions due to the return values using existing types (e.g. `ActionsListResponse`, `ThingsListResponse`). I'd prefer not add an extra point of interface interpretation, so this would append a `[subject]` to the nomenclature:
* `getLocalGetActions()`
* `getLocalGetThings()`
* `getLocalMetaGetActions()`
* `getLocalMetaGetThings()`

The same principle would apply to network functions (taking the differing network query types in regard). Your thoughts?

Can I assume the actual db connector will include matching functions? If so, then a sample implementation could look like this:

```go
func (f *DataLoader) getLocalGetActions(ctx context.Context, p graphql.ResolveParams, actionsResponse *models.ActionsListResponse) error {
	return f.databaseConnector.GetActions(ctx, p, actionsResponse)
}

**Comment by bobvanluijt** [comment]
Perfectly fine and agreed.

So the nomenclature would be: Nomenclature would be: `[action] [Location] [Function] [Concept]` (e.g.; getLocalMetaConcept)

**Comment by bobvanluijt** [comment]
I would like to add as a sidenote that @moretea mentioned that, from a backend perspective, Things and Actions are the same. This is true. However, it _might_ change in the future and I'm worried that we would have created an infrastructure that would allow for an easy change.

**Comment by etiennedi** [comment]
@moretea 
An alternative would be to strip the Connector of all knowledge of either GraphQL or REST frontend and have the interface only be BusinessLogic, such as `ListThings()`, which takes arguments that are completely independent of either front end. 

For #491 this basically means scrapping the `GetGraph()` and the newly introduced graphQL specific list things. The translation of graphql->connector could simply move into the `graphqlapi`. Thus reducing the coupling and need to duplicate methods.

I'll try and build a mini prototype (basically just modify #491), simply because that's easier to discuss on than theory.

> I'll elaborate next week.
Very interested to hear this next week.

**Comment by etiennedi** [comment]
The linked commit removes all knowledge of what APIs we have from the connector. It's sort of the other extreme of of the previous commits of #491.  (I think it doesn't actually come up in the docker-compose setup. I don't have time to debug this now, but it's more about the API design than this actually working).

thoughts on this @bobvanluijt, @JeroenStravers1?

**Comment by JeroenStravers1** [comment]
Thanks @moretea, just in time! 

A resolver in the GQL endpoint will only refer to the single Thing/Action it is a part of. This means that a (mock) resolver function for a local get thing function could look like this:

```go
func resolveLocalGetThing(p graphql.ResolveParams) (interface{}, error) {
    p.Args['weaviate_request_type'] = 'local_get_thing'
    result, err := db_connector.GetGraph(p)
    return (result, err)
}
```
Storing information about the resolver type in the resolveParams makes the request easy to parse in the dataloader's GetGraph() function (`constants` omitted for clarity).

In this case the dataloader's `GetGraph()` would refer to its `LocalGetThing()` (currently called `GetThing()`, which in turn would refer to either the database connector's `GetGraph()` or it's matching `GetThing()` (depending on [which implementation](https://github.com/creativesoftwarefdn/weaviate/issues/480#issuecomment-423905159) we go for).

**Comment by bobvanluijt** [comment]
I don't want to interfere in how close or how loose or tight the GQL implementation is coupled to the connector.

My $0.02 however, involve;
- We want to allow for other connectors like -for the sake of argument- SQLite or the sort which do not support Gremlin.
- We should not forget the filters, I assume you don't want to do filtering inside Weaviate (@moretea)?

**Comment by moretea** [comment]
I'd put the GetLocalGraph like queries in a different abstraction layer (if that layer is even needed).

I had in mind to go for something like:

```
go-swagger middleware
  |
  V
HTTP handler (boilerplate we wrote to link to GraphQL)
  |
  V
GraphQL middleware
  |
  V
GraphQL resolver
  - Implement the query resolver at a certain level (e.g. where we apply the filters).
  - Translate the ResolveParams into a domain object that describes the query.
  - Hand off this query to the database connector.
  - Collect the results, convert into a suitable data representation.
  - Then pass in the result of the query into the 'source' for the other sub-resolvers, who will only extract the information
  |
  V
Intermediate Query Representation
  |
  V
JanusGraph DB Connector
  |
  V
JanusGraph
  |
  V
Cassandra/Elastic
```

I was working on this intermediate query representation, but picked up being able to migrate the ontology structure first.

**Comment by moretea** [comment]
After reading the whole thread again, I think we agree on the design!

This Intermediate Query Representation is still needed, because we need to include relations. E.g. go from City to Airport to ConnectedAirportsByFlightRoute to Country to NameOfQueen. This is a bit hard to express without introducing a intermediate representation, especially if we should filters on this.

**Comment by JeroenStravers1** [comment]
closing, no longer an issue
