### ISSUE TITLE
GQL dataloader implementation issue

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#497]
## Background: intended request flow
1. GQL endpoint resolver calls `GetGraph()` on a connector (dataloader, currently) with a `ResolveParams` struct containing the args (filters) and the context, among others.
2. Dataloader's `GetGraph()` passes the request on to a matching function. This function wraps the actual database calls in its `Load()` fucntion to enable batching/caching and passes them on to the actual db_connector's matching functions.
3. db_connector retrieves data.

## Issue
Dataloader's `Load()` function only accepts `(context, key)` as parameters. It essentially assumes that you've decided what you want to retrieve (filters/args) before you call it. This means that passing the args (filters) along to the actual db_connector is not possible in the setup specified above.

## Options
1. Implement the dataloader directly in the db_connector(s)
2. Keep the current dataloader-as-connector loadout for REST calls, add GQL call-specific code to the db_connector(s)
3. Implement arg/filter handling in the dataloader connector
4. Suggestions?

cc: @bobvanluijt @johnciocoiu @e7dal @moretea (did I miss anyone?)
refs: gh-494 & gh-480

**Comment by JeroenStravers1** [comment]
I'd suggest either option 1 or 3 because these solutions keep the dataloader code in one location. If 3 I'd need some help with handling filters. Thoughts?

**Comment by johnciocoiu** [comment]
Keep the 'separation of concerns'-principle in mind. So, the connector needs to do the DB connection only. Weaviate's core just uses the connectors functions (independent of the chosen connector) to get the data. Dataloader should not be implemented in any of those but as a layer in between.

Filters should be of such format that they can be sent to any connector and handled by the connector itself in the connector's DB-QL.

With this in mind:
1. Implement data loader in a connector will have the consequence that when a new connector is implemented, the dataloader should re-implemented as well. This is a thing you don't want.
2. Dataloader as connector-wrapper has my preference. GQL calls should be handled separately by Weaviate and resolved using the connector functions (again, both uses the 'separation of concerns' principle).
3. Do query adjustments based on filters in the connector, building of the query object should be done in Weaviates core.

I hope this helps!

**Comment by bobvanluijt** [comment]
Additionally, @dljcollette just shared that the frontend-app will use batching by default. Which again presses for the use of data loader. 👍

**Comment by JeroenStravers1** [comment]
Thanks @johnciocoiu! I do have a follow-up question regarding your second point:
> 2. Dataloader as connector-wrapper has my preference. GQL calls should be handled separately by Weaviate and resolved using the connector functions (again, both uses the 'separation of concerns' principle).

The GQL resolvers need to use the dataloader, they pass along a `ResolveParams` struct containing all relevant data for the request. However, the `dataloader.Load()` function that passes the request from the dataloader connector-wrapper to the actual `db_connector` has no room for this struct as an arg. This would mean that the code for handling GQL resolvers with a dataloader would have to be located in another file, splitting up the dataloader implementation into two locations.

**Comment by JeroenStravers1** [comment]
@johnciocoiu showed me the solution to this issue in a meeting today, which is using the `where` parameter in the matching [functions](https://github.com/creativesoftwarefdn/weaviate/blob/2d5949a0c933f9b3f9ced28b37a3a1fa48993f58/connectors/utils/dataloader/actions.go#L54) [`ListThings()`, `ListActions()`, `ListKeys()`]. Thanks John! Closing this issue.
