### ISSUE TITLE
Clean up configuration

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#499]
There appear to be quite some things in `config/config_handler.go` that are left overs from experiments, or not (yet) implemented features.

We should align on which ones can indeed be dropped.

I would remove, from the [Environment](https://github.com/creativesoftwarefdn/weaviate/blob/1d4b50f8f2a9fb47615c0c29da6540de1f386a0e/config/config_handler.go#L47-L58) struct:
- Development
- Broker

@bobvanluijt given that this is clearly user facing operation, I'd like an 'ack' on this.

**Comment by etiennedi** [comment]
Closing as this is being addressed in #826
