### ISSUE TITLE
CLI tool to load JSON schema files into a weavaite instance

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#502]
Currently the schema is stored in JSON files.

We are moving towards storing the schema in Weaviate, and having an API available to modify the schema (#468).
Once this is done, users need to use this API to set/update the schema.

We should create a small CLI tool that will take one of the current JSON schema files, and use Weaviate's API to set the schema.

**Comment by bobvanluijt** [comment]
Thanks for creating this issue. This will move to another repo, this can be part of the SeMI-tool.
