### ISSUE TITLE
array of references in schema node properties

### ISSUE THREAD

**Issue by laura-ham** [creativesoftwarefdn/weaviate#503]
In the current design, every property can only contain one reference per data instance (Thing or Action).

To clarify, consider the following simplified ontology:

```json
"classes": [
    {
        "class": "Business",
        "properties": [
            {
                "name": "openingHours",
                "@dataType": [
                    "OpeningHours"
                ],
            }
        ]
    }, {
        "class": "OpeningHours",
        "properties": [
            {
                "name": "day",
                "@dataType": [
                    "Day"
                ],
            }, {
                "name": "opensAt",
                "@dataType": [
                    "Hour"
                ],
            }, {
                "name": "closesAt",
                "@dataType": [
                    "Hour"
                ],
            }
        ]
    }
]
```

Now, for each business, you can only point to 'OpeningHours' only once. It is not possible to point to 7 instances of OpeningHours (for each day). 

Proposed is to allow a array of references per property per Thing/Action. This makes it possible to make references to more classes in one property.

**Comment by bobvanluijt** [comment]
Good point @laura-ham 

@moretea would it be possible to add this to milestone 1?

**Comment by bobvanluijt** [comment]
@laura-ham and @JeroenStravers1 I guess this would also have an impact on the GQL responses and potential the requests?

**Comment by laura-ham** [comment]
> @laura-ham and @JeroenStravers1 I guess this would also have an impact on the GQL responses and potential the requests?

That's correct

**Comment by laura-ham** [comment]
An example in GraphQL would be: 

Query: 
```graphql
{
  Local{
    Get{
      Things{
        Business{
          openingHours{
            ...on OpeningHours{
              day{
                ...on Day{
                  day
                }
              }
              opensAt{
                ...on Hours{
                  hour
                }
              }
              opensAt{
                ...on Hours{
                  hour
                }
              }
            }
          }
        }
      }
    }
  }
}
```

result:
```graphql
{
  "data": {
    "Local": {
      "Get": {
        "Things": {
          "Business": [
			  {
				  "openingHours": [{
					  "day": {
						  "day": "Monday"
					  },
					  "opensAt": {
						  "hour": 09
					  },
					  "closesAt": {
						  "hour": 17
					  }
				  }, {
					  "day": {
						  "day": "Tuesday"
					  },
					  "opensAt": {
						  "hour": 09
					  },
					  "closesAt": {
						  "hour": 22
					  }
				  }]
			  }
		  ]
        }
      }
    }
  }
}
```

The difference is thus that the property 'openingHours' of 'Business' resolves in a list (instead of just one property value, which is in this case a reference).

**Comment by bobvanluijt** [comment]
Awesome, is this in line with your design @moretea?

**Comment by moretea** [comment]
I don't see in this example where we mark OpeningHours to be a list/set.

I believe that a GraphQL field cannot be both a single reference, and a list of references at the same.

**Comment by laura-ham** [comment]
We could make all references lists in GraphQL?

**Comment by bobvanluijt** [comment]
Yes, we can assume a list always. If there is just one cref it is a list with one reference.

What is important though, is to think of dealing with _updates_ on a thing or action. If you update a cref, do you _add_ those crefs or do you overwrite them?

**Comment by moretea** [comment]
I would suggest to introduce a [cardinality](https://en.wikipedia.org/wiki/Cardinality) of properties, instead of always returning a list.

Based on this information, we can generate the proper GraphQL schema / resolver.

```
   "SemanticSchemaClassProperty": {
      "properties": {
        "@dataType": {
          "description": "Can be a reference ($cref) to another type when starts wit
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "cardinality": {
          "description": "The cardinality of this property. If you want to store mor
          "type": "string",
          "enum": [
            "atMostOne",
            "many"
          ]
        },
        "description": {
          "description": "Description of the property",
          "type": "string"
        },
        "name": {
          "description": "Name of the property as URI relative to the schema URL.",
          "type": "string"
        },
        "keywords": {
          "description": "Describes the kind of class. For example Geolocation for t
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "kind": {
                "type": "string"
              },
              "weight": {
                "type": "number",
                "format": "float"
              }
            }
          }
        }
      },
      "type": "object"
    },

```

**Comment by moretea** [comment]
For updating a list of crefs, I would go for the semantics of 'setting' the value of a property. So it would overwrite all existing references.

Note that I can't really guarantee in any case what the actual behavior would be on the resulting data if two concurrent requests would modify the same properties; AFAIK Janus doesn't support the required primitives to allow us to give these guarantees.

**Comment by bobvanluijt** [comment]
I think this one can be closed thanks to the introduction of cardinality. Isn't it @moretea?

**Comment by moretea** [comment]
Yep.
