### ISSUE TITLE
Update and add docs, Travis and prototype

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#504]
- [ ] Update docs structure
- [ ] Improve existing docs
- [ ] Update vision docs add getting started
- [ ] Update readme
- [ ] ~Merge prototype and Weaviate repos~
- [ ] Fix Travis build issues for Master and bins.
- [ ] create label for GQL prototype

**Comment by etiennedi** [comment]
@bobvanluijt can this be closed or is there anything left to do?

**Comment by bobvanluijt** [comment]
Nope, finished with @idcrosby's commit.
