### ISSUE TITLE
Inconsistent http error responses

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#506]
## Issue
Our error responses are inconsistent. I would propose a uniform approach so our users always know which attribute to access when looking for an error message. 

## Background
I listed some reproducible examples below using Postman and a Dummy config local Weaviate and sending the specified queries to the `/graphql` extension (note: this issue is not endpoint-specific). The actual requests/responses are not of interest here, my point is about the response type.

#### 1. Unprocessable query
This query returns a 400 (bad request) in the header and a JSON Body

Request body: 
```
[]
```
To: /graphql

Response:
```
{
    "code": 400,
    "message": "parsing body body from \"\" failed, because json: cannot unmarshal object into Go value of type models.GraphQLQuery"
}
```
#### 2. Empty query
Only returns a 422 (unprocessable entity) code in the header

Request body: 
```
{}
```
To: /graphql

Response:
```
{}
```

#### 3. Valid GQL query asking for attribute of a class that has no instances in the database
Returns a nested JSON error in the body and a 200 in the header. 
*Note that this request returns a 200 because the request itself is valid.

Request body:
```
{"query":"{\n  Local {\n    Get {\n      Things {\n        TestThing {\n          uuid\n        }\n      }\n    }\n  }\n}\n","variables":null,"operationName":null}
```
To: /graphql

Response:
```json
{
    "data": {
        "Local": null
    },
    "errors": [
        {
            "locations": [
                {
                    "column": 3,
                    "line": 2
                }
            ],
            "message": "runtime error: invalid memory address or nil pointer dereference",
            "path": [
                "Local"
            ]
        }
    ]
}
```
Three queries resulting in an error, three different types of output.
## Questions
* Do we want to standardize error output?
* Assuming standardisation is preferred, which return value do we want to use?
* Any of the options in the example?
* Something else entirely?

cc: @moretea @bobvanluijt

**Comment by JeroenStravers1** [comment]
Note that the third example returns a 200 because the request is valid, it returns an error because it cannot find anything in the database matching the query.

Returning error codes for a request in the header only is somewhat of a problem for batch requests too, as a batch request can contain multiple failed requests. 

I'd prefer returning a nested error like in the third example. I like the consistency with successful request responses, and this format is easy to use. The `locations` and `path` fields would be optional. This would also solve the issue with returning batched request errors.

**Comment by moretea** [comment]
To me only the first error does not make sense. Could you link to the implementation source code on github here?

The second field is missing the `query` property. So yes, not acceptable request. We could extend the error message a bit.

The third case is correct. We accept the query, it's "valid" (syntax wise), but resolving fails because we did not implement the resolvers yet.

**Comment by bobvanluijt** [comment]
Yes indeed.

We have the REST errors (as described in the open API specs) and the GQL based errors.

What I don’t know is if a proper request to the GQL endpoint should also return a 200.

**Comment by JeroenStravers1** [comment]
it's located [here](https://github.com/creativesoftwarefdn/weaviate/blob/649b3c3b02d1a70f7d9a033538591a9d6c08e865/restapi/configure_weaviate.go#L1200). I did correct a mistake in the error response above, should have been models.GraphQLQuery

**Comment by moretea** [comment]
That makes sense. Because that endpoint handler is accepting just _one_ query at a time. It does not support batching. Did you link the correct handler?

Or do we now want to use just one HTTP endpoint for both normal GraphQL queries, and batched queries?

**Comment by JeroenStravers1** [comment]
@moretea my point is not about the response (or the request) itself but about the structure of the JSON response body. We're still using separate endpoints, I should have clarified that!

@general The first example (return nothing, only a header) does pose a problem to batch request handling. I can't use the header for errors for individual requests in a batch.

**Comment by moretea** [comment]
Yes you can. You could collect the results, and then see if one fails. Then you return a HTTP error. To do this, you'd probably need to introduce a intermediate data structure, which would not only store a GraphQueryResult, but also a bool to denote if it's a fatal error or not.


```
api.handler = func (http params) http.Middleware {

  struct batchResult {
    result *graphql.GraphqlResponse
    isFatal bool
  }

 /// loop over everything

/// in goroutine:
go func() {
  response_channel <- batchResult { .... }
}

/// Then collect
var graphlResponses []models.GraphQLQueryResultSomethingModel
for _, response in response_channel {
   if response.isFatal {
      return graphql.SomeFatalErrorResponse().WithPayload(error)
  } else {
    // append to graphqlResponses
  }
}
payload := graphqlResponses
return graphql.NewGraphQlOKResponse().WithPayload(payload)

}
```
IMHO you should do that in any case for "fatal" errors (the ones that cause a return graphql.SomeErrorState in the current handler).

**Comment by JeroenStravers1** [comment]
I'm afraid that wouldn't work, I can't let an entire batch fail because one or more of the requests it contains fails (well I can, but I really shouldn't). Say we put requests A and B in a single batch request. The only relation request A has to request B is that they're both wrapped in the same request. Request A wouldn't fail if it and request B were sent separately, the same should hold true when they're batched. 

I view it as taking the bus to work with random people; whether they're late for their jobs or not does not and should not impact you.

**Comment by bobvanluijt** [comment]
I agree with you @JeroenStravers1. Besides this, the error is part of the GQL response. It is a _correct_ REST response (therefore 200) but an incorrect GQL result (therefore the error is in the response).

@dljcollette this (⬆️) is correct, right?

**Comment by JeroenStravers1** [comment]
In retrospect I should have omitted the graphql case, as that is indeed a different case than when a request itself produces an error. If we ignore the third case, are the first and second case behaving as expected? 

It's the second case, the one that returns nothing, that has me worried. How should I handle such a response as part of a batch? I can't set the header of the batch request to the response code of any single batched request (the rest of them have headers too!), and I don't have a response body to work with.

**Comment by bobvanluijt** [comment]
Well, per bullet.

1. This _is_ correct. It can't model `models.GraphQLQuery` based on an array. Are you sure that the HTTP-response is a 400 and not 200 but that _graphql_ sends a 400? There is nothing [in the code](https://github.com/creativesoftwarefdn/weaviate/blob/develop/restapi/configure_weaviate.go#L1200) that generates a 400, only 200, 401, 403 and 422.
2. This is correct
3. This is correct too.

There is another route you can take too. That might be way easier and faster to implement which I outlined [here](https://github.com/creativesoftwarefdn/weaviate/issues/498#issuecomment-428630507).

**Comment by bobvanluijt** [comment]
What is the status of this issue @JeroenStravers1?

**Comment by JeroenStravers1** [comment]
Currently the GQL batch endpoint returns batched request errors that would normally be returned as a header status code (say a `422`) by using the field that errors caused by GraphQL query errors would inhabit:
```
[
  {
    "errors": [
      {
        "message": "error message"
      }
    ]
  },
  ... other responses
]
```
The batch create endpoints produce a similar response, but the error message is nested deeper:
```
[
  {
    "result": {
      "errors": {
        "error": [
          {
            "message": "error message"
          }
        ]
      }
    }
  },
    ... other responses
]
```
The `"result"` field also has a property that contains either `"SUCCESS"`, `"PENDING"` or `"FAILED"`, depending on the request result, so it has some added value.

The above implementation works. We could keep it like this, or we could streamline the batch create endpoint error responses to match the batch GQL endpoint error responses (meaning eliminating the `"result"` and `"errors"` layers, and renaming the `"error"` layer to errors).

**Comment by JeroenStravers1** [comment]
If this is acceptable, then yes :) I'll update the batching doc to reflect this.

**Comment by JeroenStravers1** [comment]
Closing as discussed
