### ISSUE TITLE
Implications of API for schema change for schema meta data 

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#507]
Now that I'm working on having the schema being modifiable by an API,
I have some open questions about how to deal with the metadata associated to a      schema.

I could simply add the following method to the schema manager interface:
`SetMeta(kind kind.Kind, atContext string, maintainer string, name string) error`   

The versioning is a bit more tricky.

To facilitate importing existing schema's and versions, I could add a SetVersion function (see below), that would only allow you to set the version once, and then will only allow you to bump it to strictly higher versions. 

API  operations that drop or rename a class / property would automatically increase the  major number, adding a new class/property will increase the minor number, and updating the keywords of a class/property will increment the patch level.

```
SetVersion(kind kind.Kind, version string) error
```

Of course, we could also simply ignore the version field completely and allow the end user to set any version they want.

**Comment by bobvanluijt** [comment]
What would be the use case of versioning for the schema?

**Comment by moretea** [comment]
I don't know? You added a version field in the original design. What was it's purpose back then?

Alternatively we could simply drop this 'version' column. I do think that most databases do not publish a version of their database schema.

**Comment by bobvanluijt** [comment]
Aha, I see, did not understand it in this context.

The goal of the `.version` field _was_ related to horizontal scaling of a Weaviate. In the previous setup (id est, with ontologies as JSON files). If somebody would be using `w+1` on the same DB it would be part of validating that it would be the same ontologies.

With the new setup this is not an issue anymore, therefore, versioning can be dropped.
