### ISSUE TITLE
Implement batch CRUD request handling

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#508]
## Batch request handling
Weaviate's Thing and Action Create [endpoints](https://github.com/creativesoftwarefdn/weaviate/blob/649b3c3b02d1a70f7d9a033538591a9d6c08e865/restapi/configure_weaviate.go#L252) can't currently handle incoming batch requests (as specified [here](https://www.apollographql.com/docs/link/links/batch-http.html)). 

A successful implementation consists of batch request handling, acceptance test coverage and [documentation](https://www.github.com/creativesoftwarefdn/weaviate/blob/feature/batch_graphql/docs/batch_request_processing.md) of how Weaviate handles batch requests for these two endpoints. An example of how to implement batch request handling in Weaviate can be found [here](https://www.github.com/creativesoftwarefdn/weaviate/blob/74fed9c2415890a183b063ab75243102afee56c4/restapi/configure_weaviate.go#L1260).

#### Batch request handling
- [x] ThingsCreate
- [x] ActionsCreate
#### Acceptance test coverage
note: each individual endpoint needs to be included in at least 1 test
- [x] ThingsCreate
- [x] ActionsCreate
#### Documentation
note: tick boxes only after validation/proofreading
- [x] Sending a batch request to Weaviate
- [x] Receiving a batch response from Weaviate
- [x] List of endpoints

--edit: updated text and to-do lists as discussed with @bobvanluijt

**Comment by bobvanluijt** [comment]
Few thoughts;

1. Keep in mind the `sync` value. If `async == true`, the result is always a 202 and the status should be `PENDING`.  If `async == false` a 200 can be returned with FAILED or SUCCESS.
2. You should be able to handle _all_ requests with the functions that are created by @moretea. For example: if you create an action. You should be able to use `actions.WeaviateActionsCreateHandlerFunc()`.

**Comment by JeroenStravers1** [comment]
Batching is implemented and documented. Closing this issue.
