### ISSUE TITLE
Implement Graphql groupBy function

### ISSUE THREAD

**Issue by laura-ham** [creativesoftwarefdn/weaviate#511]
To aggregate GraphQL results.

**Comment by laura-ham** [comment]
@bobvanluijt Could you answer my question on your gist https://gist.github.com/bobvanluijt/a6f812589095f7435e4e8a99a7f8fef6)? Now I don't see how to practically implement this..

**Comment by bobvanluijt** [comment]
Yes @laura-ham: see: https://gist.github.com/bobvanluijt/a6f812589095f7435e4e8a99a7f8fef6#gistcomment-2713015

**Comment by laura-ham** [comment]
@moretea @JeroenStravers1 @bobvanluijt 

New groupBy design:

``` graphql
{
  Local{
    Aggregate(where:...){
      Things{
        City(groupBy:["country", "Country", "name"]){     #has to be path/list because of possible crefs
          avg{
            population      # any numeric property
          }
          min{
            population      # any numeric property
          }
          max{
            population      # any numeric property
          }
          median{
            population      # any numeric property
          }
          sum{
            population      # any numeric property
          }
          mode{
            population      # any numeric property
          }
          percentile(from: 0.25, to: 0.75){
            population      # any numeric property
          }
          count{
            uuid   # any property possible
          }
          groupedBy{ #indicates the groups
            country{
              ... on Country {
                name
              }
            }
          }
        }
      }
    }
  }
}
```

If no comments/suggestions, I will implement this in the prototype asap! :)

**Comment by bobvanluijt** [comment]
@laura-ham does this solve the problem as stated yesterday by you and @JeroenStravers1?

**Comment by JeroenStravers1** [comment]
Looks good!

**Comment by bobvanluijt** [comment]
Cool, in that case I would move it forward. Please don't forget to update the docs ;-)
@JeroenStravers1 can you pick it up when it's in the prototype?

**Comment by etiennedi** [comment]
Closing as aggregate has been implemented in Weaviate Core and released for quite some time.
