### ISSUE TITLE
Batch request error response types (422)

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#513]
## Issue
Currently a HTTP request that causes a 422 error receives a response with `header: 422` and `body: {}`. This is fine for single requests. However, when this request is part of a batch it has no individual header; a batch request is a single HTTP request, and the header is reserved for the batch request itself, not the batched requests it contains. This means that a batched request that causes a 422 can return nothing but `{}`.

### Intermediate solution
For now I implemented this fix: a batch request containing a batched request that causes a 422 will return a batch response in the following format:
```
[
    {
        "errors": [
            "location": "",
            "message": "422: The request was well-formed but was unable to be followed due to semantic errors.",
            "path": ""
        ]
    },
    <other queries>
]
```
This way devs using Weaviate have some feedback. I implemented this example for the batch GraphQL endpoint, it uses this structure because the batch has to be an array of GraphQLResponses. I can't use HTTP errors here, the error is structured like this because it is in fact a GraphQL error response object. 

### Intermediate issue status
Other endpoints do not use this error format, neither do errors returned at the batch request level. This should be streamlined.

## Proposed solution
We need to discuss the error return type, what kind of response is desirable here? Should we be more permissive in return types? How can we ensure that both GQL and CRUD batch endpoints return errors in the same format?

**Comment by JeroenStravers1** [comment]
Don't forget to update the [doc](https://github.com/creativesoftwarefdn/weaviate/edit/feature/batch_graphql/docs/batch_request_processing.md) when this is resolved.

**Comment by JeroenStravers1** [comment]
I started implementing batched requests for the ActionCreate endpoint and encountered a similar problem; the endpoint returns an [ActionGetResponse](https://github.com/creativesoftwarefdn/weaviate/blob/10421ed68425116396834d145f0581ae8a0d786b/models/action_get_response.go#L30) which has no field for error messages. A failed request instead returns an error code in the header and an empty body. This is incompatible with batching and has to be resolved. I can think of two options for now:

1. **Use `Middleware.responder` as return type**: 
This return type is as generic as possible. 
**Pros**: it's an easy fix. 
**Cons**: our users have to interpret Weaviate's responses. 

2. **Edit the existing design for non-batched endpoints**: 
Add an error field to all regular response types, change existing functions to make use of this new error field instead of or in addition to the request header. 
**Pros**: Weaviate's output is consistent and clear. 
**Cons**: takes time to implement.

3. Suggestions?


@moretea @bobvanluijt @anyoneelse?

For the record: I'm not in favor of the first option, it really decreases Weaviate's ease of use.

**Comment by moretea** [comment]
Not going to get into details here, but my 2 cents:

Go for a few extra simple HTTP endpoints.

We already have the GetThings and GetActions endpoint, so those are already batched.

If we want to have options to insert/update/delete multiple things or actions in one request, we could follow the design layed out for GetThings/GetActions.

Alternatively, this might be a nice 3rd party middleware that we could sell separately as an add-on.

**Comment by bobvanluijt** [comment]
@JeroenStravers1 as discussed, closing this one.
