### ISSUE TITLE
Implement Network queries

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#515]
In the GraphQL design and prototype, there is a new root function called `Network{}`

## Description

Like the `Local{}` implementation the `Network{}` implementation should become part of the GQL API and it should resolve to [this](https://github.com/creativesoftwarefdn/weaviate/blob/develop/network/graphql_resolver.go#L8) resolver.

## Docs

- **Docs**: https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/graphql_network.md
- **Prototype**: https://github.com/creativesoftwarefdn/weaviate/tree/feature/travis-docs/graphqlapi/prototype
- **Schema**: https://github.com/creativesoftwarefdn/weaviate/tree/feature/travis-docs/test/graphql_schema

_Note: locations of these files might change during development_

**Comment by JeroenStravers1** [comment]
Network queries are implemented as in the Prototype. Closing this issue.
