### ISSUE TITLE
How to deal with validating  classes & properties names in the Contextionary

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#517]
Now that we're working on #486, we need to think about the expected behavior of validating the names in the schema against a contextionary.

We cannot simply bail out anymore, because we won't be able to change the schema when Weaviate is not running.

There are a few options:

- Disable some systems
  - Weaviate will not register itself on the network, local queries will work.
  - Disable all functionality except the schema API
- Just continue, but log a warning to the output. Return errors when users try to fuzzy search.

I would suggest to go for the last option.

**Comment by bobvanluijt** [comment]
It is mandatory for class names, properties, and keywords to be in the contextionary. Values not (maybe we want this in the future, though, but definitely not now).

For class names or property names that are a contraction of multiple words, please read [this doc](https://github.com/creativesoftwarefdn/weaviate/blob/feature/travis-docs/docs/en/ontology.md#camelcase).

## Suggested workflow

1. Weaviate startup is initiated without any schema.
2. When adding a thing or action (via REST), the class, properties, and keywords are validated against the contextionary. If _any_ of those is not in the contextionary, fail to add the thing or action (for example, through the appropriate http-error)
3. If a Weaviate is stopped, the contextionary is changed, and after a boot, ideally, the Weaviate validates against the contextionary again. If the words are not in the contextionary, it fails.

Question @moretea: I'm aware that bullet 3 might be suboptimal, but bullet 2 is important to maintain at all times. Do you have alternative suggestions?

**Comment by moretea** [comment]
Yes, this was what I had implemented before. That has been working for a
few months now.

However, there will be no way to change the database schema without running
Weaviate when I merge my current PR.

Therefore you could brick the entire system if the contextionary is
updated, and a word is not present anymore.

Hence my question, how do you want to deal with this, and my suggestions.

With this added context, could you look again at my question?

We _could_ implemented a process that would check that we would only create
larger contextionaries. However, if we make a slight error, you could brick
all Weaviate clusters.

Op ma 15 okt. 2018 09:59 schreef Bob van Luijt <notifications@github.com>:

**Comment by bobvanluijt** [comment]
Aha, I see. Two additional quesions;
1. How difficult would it be to validate the exsisting schema (when a Weaviate restarts) agains the current contextionary?
2. A Weaviate-Network needs to have _one_ contextionary (to always work in the same context). This means that we need to share the contextionary when joining but also when _re-joining_ a network. This is why I introduced the MD5, this MD5 can be used to validate the contextionary, both locally and over the network.

PS:
About the types of searches, please keep @laura-ham's [docs](https://github.com/creativesoftwarefdn/weaviate/tree/feature/travis-docs/docs/en) in mind, they are very clear about what a Weaviate can do.

**Comment by moretea** [comment]
It is not difficult at all to validate the schema when it starts up. But what if it fails? That is my question from the beginning; how do we handle that failure scenario. If we abort, we **can not recover!** Why not? Because we need a **running version** to change the schema via the API.

I don't see how this network  is related to this? IMHO it's orthogonal. My only question is about how to handle the situation when the verification fails.
