### ISSUE TITLE
Behavior adding multiple cross-refs and network cross-refs

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#518]
There are a few UX challenges we need to overcome related to network crossrefs and when updating a thing or action. The goal of this thread is to cut the knot on these topics.

# Adding +1 Ref to a thing or action

Based on the [schema](https://github.com/creativesoftwarefdn/weaviate/blob/e826024414999a66f50da2004d19e9275a3e3321/openapi-specs/schema.json) we will update a thing like this: `PUT /weaviate/things/{thingId} -d {}`. When updating the cross-reference to a thing, the behavior of the above will result in Weaviate overwriting the relations. If a thing has many references pointing out and a user wants to add 1. They first need to;
1. Lookup all refs
2. Do a PUT and add `many refs + 1 new ref`

**Question:**
What can we introduce to allow users to add or overwrite?

**Suggestion I:**
We could add it to the endpoint like: `PUT /things/{thingId}/{refUpdateType} -d {}`.
- `replace` = Replaces all refs.
- `add` = Adds new refs
- `nil` = act as `replace`

**Suggestion II:**
- Maybe _only_ allowing PATCHES instead of UPDATES on Things and Actions solve this automatically.
- A PATCH automatically solves this (_not sure_???)

**Misc notes:**
_Note: the equivalent happens when deleting a single ref._

# Local and Network Refs

Because the core proposition has changed (id est, _Weaviates are allowed to know about the content of each others' ontologies_), we can now tell a Weaviate where a thing or action is located. 

**Suggestion for a Solution - Set the location of a crossref in the ontology:** 
We can set the location in the ontology (the following example is a suggestion, syntax can be different)

```json
[{
	"name": "testCref",
	"@dataType": [
		"weaviate-A/TestThing1", "weaviate-B/TestThing2", "/TestThing3", "localhost/TestThing4"
	],
	"description": "Value of testCref."
}]
```

This means that we _don't_ have to set a location when adding a new Thing or Action anymore. But it also means that the schema needs to be updated when a new Weaviate is added to the network.

Please share what y'all think.

**Comment by bobvanluijt** [comment]
## About adding refs to a thing or action
Sounds good and agreed. Can you update the [schema.json](https://raw.githubusercontent.com/creativesoftwarefdn/weaviate/b3c316fd85b041bc59a369940fc4e43cfd7fe3ec/openapi-specs/schema.json) or shall I do this with the above in mind? I will make sure this also becomes part of the docs.

## About the Local and Network Refs
Any suggestions for this?

**Comment by moretea** [comment]
So what do you agree to exactly? to keeping things simple, or adding these extra endpoints?.

W.r.t. local and network references, any delimiter goes. It's surprising how we're slowing evolving towards something that is like RDF, but with added fuzzy search.

**Comment by bobvanluijt** [comment]
1. Agreed to [this point](https://github.com/creativesoftwarefdn/weaviate/issues/518#issuecomment-429850311) I couldn't find it in the schema so I assumed this is not implemented yet.
2. RDF has always been an inspiration (no joke btw). In the original idea, RDF mapped completely to Weaviate (and it still can). Weaviate was like (dare I say) RDF++ :-)

**Comment by bobvanluijt** [comment]
Closing because the issue is split into two news issues.
