### ISSUE TITLE
Update improved Local{} functions

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#519]
The `Local{}` GQL functions are updated.

These updates are reflected;
- In the docs which you can find [here](https://github.com/creativesoftwarefdn/weaviate/tree/feature/travis-docs/docs/en).
- In the prototype which you can find [here](https://github.com/creativesoftwarefdn/weaviate/tree/feature/travis-docs/graphqlapi/prototype).

## Todo

- [x] implement updated functions as described in prototype and docs.
- [x] update tests and make them pass.

_note: the location of `tree/feature/travis-docs` will probably soon merge into `tree/develop`_

**Comment by JeroenStravers1** [comment]
Closing, this has been resolved (I just failed to mention this issue in my commits)
