### ISSUE TITLE
Support returning multiple errors in a ErrorReponse

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#521]
I propose to change the ErrorResponse Swagger spec to:

```json
{
    "ErrorResponse": {
      "description": "An error response given by Weaviate end-points.",
      "properties": {
        "error": {
          "items": {
            "properties": {
              "message": {
                "type": "string"
              }    
            },   
            "type": "object"
          },   
          "type": "array"
        }    
      },   
      "type": "object"
    }
}
```

This will allow is to return multiple different errors.

I would also suggest to add error categories/subcomponents; this might be used to mark that the error is due to e.g. an ungrounded schema (as described in #520).

**Comment by bobvanluijt** [comment]
You need help with the implementation?

**Comment by moretea** [comment]
If you have some time to spare, then yes please!

Most of the work will be 'fixing' the other places where this is used, and maybe even removing a few string concatenations.

**Comment by bobvanluijt** [comment]
Sure, what would be best, fork off `tree/develop` or fork off `tree/feature/janusgaph`?

**Comment by moretea** [comment]
Already implemented in gh-521.
