### ISSUE TITLE
Fine grained property value operations

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#524]
Now that we have https://github.com/creativesoftwarefdn/weaviate/issues/503, we want to support more fine grained operations on the value of a property, if that value is a reference, and has a cardinality > 1.

For those properties, we'll support the following API endpoints. For other properties, we will return the Unproessable Entity HTTP error.

| verb | path | data | action |
|-|-|-|-|
| POST | `/things/{id}/properties/{name}`| `{"$cref": "uuid", "type": "Thing"}` | Add a single reference
| PUT  | `/things/{id}/properties/{name}` | `[ { "$cref": "uuid", ...}, {...}]` | Replace all references
| DELETE |  `/things/{id}/properties/{name}` | `{"$cref": "uuid", "type": "Thing"}` | Delete a specific cref from this property value.

Based on the discussions in https://github.com/creativesoftwarefdn/weaviate/issues/518.

**Comment by bobvanluijt** [comment]
Shall I add these in the schema @moretea? This does not include the actual implementation obviously

**Comment by bobvanluijt** [comment]
Note, updated the data to reflect: `$ref: '#/definitions/SingleRef'`

**Comment by moretea** [comment]
> Note, updated the data to reflect: `$ref: '#/definitions/SingleRef'`

Could you next time split the update of the specification, and the generation in two commits? [This commit](https://github.com/creativesoftwarefdn/weaviate/commit/b4e8a5c94830fd7851207712782790bcb22d40eb) is a bit harder to review :see_no_evil:

**Comment by bobvanluijt** [comment]
Check 😄👍

**Comment by moretea** [comment]
This is not implemented yet.

**Comment by bobvanluijt** [comment]
I'll pick this up tomorrow @moretea 👍

**Comment by moretea** [comment]
This is quite tricky actually. It was a note to self.

**Comment by bobvanluijt** [comment]
👍
