### ISSUE TITLE
Skip failing tests for now

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#530]

**Comment by bobvanluijt** [comment]
Depending on when @JeroenStravers1 will have the GQL issues with the tests resolved, we can keep those tests in `develop`. I believe that the fails are the majority.

**Comment by moretea** [comment]
I would like to get back to a green development branch, and keep it that way.

Now it takes quite some effort to de-cypher if a branch is good to go, or broken.

**Comment by bobvanluijt** [comment]
Fair point, in that case, we need to move the node testing to a new branch until Jeroen has fixed it.

@JeroenStravers1 shall I set this up for you or can you do this yourself?

**Comment by JeroenStravers1** [comment]
If you'd be so kind, I'm not familiar with how to do this. Happy to learn of course, but I think it'd be helpful to have this up asap.

**Comment by moretea** [comment]
You can add 
```
func TestSomething(t *testing.T) {
  t.Skip("reason") // 'reason" is optional
  // or
  t.Skip()
}
```

See the second code snippet in here: https://golang.org/pkg/testing/
