### ISSUE TITLE
Document what is required to use docker-compose setup

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#534]
To be included in the documentation:

1. `docker` and `docker-compose` must be installed locally
2. Default Ram limits for docker (2GB - at least on OS X) are not enough for weaviate. The limits have to be increased to at least X GB (I will add an exact number later, after some trial and error)
3. The setup can be started with `docker-compose -f docker-compose-dev.yml up` from the project root. This spins up weaviate, as well as the demo importer. Weaviate is ready to be used as soon as the demo importer has finished with exit code `0`.

Step 3 is not ideal yet as it is semi-manual, we are about to improve it, as part of #525. After that, we'll probably have a simple script that is blocking until the import has succeeded or finally failed.

**Comment by bobvanluijt** [comment]
Thanks @etiennedi, the RAM is also based on the size of the contextionary. I will make sure to add this to the docs.

**Comment by etiennedi** [comment]
Just FYI: The process I have described is to start up the dev-setup. Since we import a fixed set of demo-data, I'd assume the size of the contextionary is also fixed? (At least until the user imports their own data).

**Comment by etiennedi** [comment]
Ran some test on the memory requirements:

| Memory Limit | Outcome |
| --- | --- |
| 2 GB | ❌ elasticsearch exits with 137 |
| **2.5 GB** | ✅  importer runs successfully |
| 3 GB | ✅  importer runs successfully |

It seems with the current setup 2.5GB is the sweetspot. To have some headroom, I'd recommend mentioning 3GB in the docs. 

It might also be worth explaining the symptoms: I.e.

> "If the `weaviate_index` container fails with exit code `137` make sure your Docker limits are set toat least 3GB"

**Comment by moretea** [comment]
Alternatively, we could check if we could reduce the memory needs for Elastic by setting e.g. `-Xmx`, or some other [JVM flags](https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits) to detect the amount of memory available.

But this is probably the easier route yes.

**Comment by bobvanluijt** [comment]
Hi @moretea, friendly reminder for a suggestion/hint on how an end user currently is able to change the location of the Contextionary. Thx

**Comment by moretea** [comment]
"changing the location" is too imprecise. If the end-user wants to use a different contextionary, something like this would be sufficient:

```
FROM semi/weaviate
COPY ./new_contextoinary /location/of/contextionary/in/docker/image
```

**Comment by bobvanluijt** [comment]
Super, check, thanks

**Comment by bobvanluijt** [comment]
FMI: https://github.com/creativesoftwarefdn/weaviate/issues/549#issuecomment-433075246

**Comment by etiennedi** [comment]
Closing as this is part of the Getting Started Guides in the meantime.
