### ISSUE TITLE
Add a hosted swagger UI (just like GraphiQL)

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#546]

**Comment by bobvanluijt** [comment]
Hi @moretea, this will be added to the website as part of the docs.

**Comment by moretea** [comment]
That's not exactly the same as what is possible with GraphiQL today already.

As you can see in the comit that closes this issue, it's pretty much re-using the work I did for the GraphiQL UI.

**Comment by bobvanluijt** [comment]
I know, but I don't find it very clean to have a UI dangling (if you will) from Weaviate. I also understand the value for development purposes, but in due time I would like to split them off, maybe even make them part of the Playground.
