### ISSUE TITLE
Implement groupBy in Weaviate's GQL

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#548]
The groupBy function as outlined in [this gist](https://gist.github.com/bobvanluijt/a6f812589095f7435e4e8a99a7f8fef6) should be implemented in the Local and Network functions.

# Important Notes

- The `Network{}` and `Local{}` functionalities are equivalents from a GQL implementation PoV.
- Exact documentation will be available [here](https://github.com/creativesoftwarefdn/weaviate/blob/feature/travis-docs/docs/en/use/graphql_grouping.md)
- The gist is not definitive yet (24 Oct) but the solution outline will be similar.

# Misc.

Related to #511

**Comment by JeroenStravers1** [comment]
GroupBy filter and Aggregation is implemented in Weaviate, closing this issue
