### ISSUE TITLE
Determine image tagging strategy

### ISSUE THREAD

**Issue by idcrosby** [creativesoftwarefdn/weaviate#549]
- CI system (Travis) will tag and push docker images
- Use standard semvar tagging (?)
- We (may) want to tag and push different branches. How should these be named?
- Same for different contextionaries (?)

**Comment by moretea** [comment]
I would propose:

* Tag as the same version that is used in the current .travis.yml file. Search for `jq` in Travis.
* Master is the "last released" branch. From this branch, genereate images tagged as `semi/weaviate:vx.y.z`, `s/w:vx.y`, `s/w:vx` and `s/w:latest`.
* Publish a `s/w:unstable` for each `development` push.

No need to push for PR's / other branches

**Comment by bobvanluijt** [comment]
Additionally;
1. Please note: https://github.com/creativesoftwarefdn/weaviate/blob/feature/travis-docs/docs/en/contribute/contributing.md#versioning
2. Let's indeed not _publish_ different branches. It would be nice though if you can share how a dev can simply build a specific branch-based Docker. I will add that to the docs.

**Comment by bobvanluijt** [comment]
Additionally;
1. Please note: https://github.com/creativesoftwarefdn/weaviate/blob/feature/travis-docs/docs/en/contribute/contributing.md#versioning
2. Let's indeed not _publish_ different branches. It would be nice though if you can share how a dev can simply build a specific branch-based Docker. I will add that to the docs.
3. Please note it is `creativesoftwarefdn/weaviate:vx.y.z` etc _not_ `semi/weaviate:vx.y.z` etc.

**Comment by bobvanluijt** [comment]
Additionally;
1. Please note: https://github.com/creativesoftwarefdn/weaviate/blob/feature/travis-docs/docs/en/contribute/contributing.md#versioning
2. Let's indeed not _publish_ different branches. It would be nice though if you can share how a dev can simply build a specific branch-based Docker. I will add that to the docs.
3. @moretea please note it is `creativesoftwarefdn/weaviate:vx.y.z` etc _not_ `semi/weaviate:vx.y.z` etc.

**Comment by bobvanluijt** [comment]
@idcrosby and @moretea additional question regarding CI system's behavior.

If someone pushes to `develop` or `master`:
- Travis will tag and push docker images.

**Question**: what will be the behavior be _if the version number is not changed_?
1. Travis fails the build with the error that the version needs to be bumped. Or;
2. Travis auto-bumps the PATCH number + 1, pushes the Docker image with the new version _and_ commits back the new version number. Or;
3. Travis succeeds and overwrites the Docker image with the same version number.

This will be less of a problem with `master` because merging an existing version number will fail.

**Comment by idcrosby** [comment]
To build a specific branch-based Docker image you can run:

`docker-compose -f docker-compose-dev.yml build weaviate`

This image will be named and tagged as specified in the compose file (currently: `weaviate/dev-server:latest`). The compose file should then be update to reflect our naming decision. We could also add an optional variable to overwrite the `latest` tag. 

Re: _if the version number is not changed?_

- Since the `develop` will always use the `usntable` tag (as proposed above), this will not be an issue.
- For `master` as you mention, this will result in Travis failing the build.

**Comment by bobvanluijt** [comment]
@idcrosby can we close this issue?

**Comment by idcrosby** [comment]
Yup, closing now
