### ISSUE TITLE
Slight confusion because of the use of the word keyword in full blown ontology example 

### ISSUE THREAD

**Issue by michaverhagen** [creativesoftwarefdn/weaviate#557]
In the full blown ontology example, you have a few (five to be exact) times the word "keyword" as an example for a value for keyword. It would be clearer if you would replace this with a real relevant keyword.

"keywords": [
            {
              "keyword": "keyword",
              "weight": 1
            }

https://github.com/creativesoftwarefdn/weaviate/blob/feature/travis-docs/docs/en/use/ontology-schema.md

**Comment by etiennedi** [comment]
@bobvanluijt @michaverhagen has this been resolved in the meantime? The above link is now dead.

**Comment by bobvanluijt** [comment]
Yes
