### ISSUE TITLE
Replace JanusGraph in-repo image

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#564]
Replace the reference in the `docker-compose.yml` and `docker-compose-test.yml` files with https://github.com/creativesoftwarefdn/janusgraph-docker/

**Comment by moretea** [comment]
Also `git rm -rf tools/dev/janusgraph-docker` then please :)

**Comment by idcrosby** [comment]
Linked commit to wrong issue: https://github.com/creativesoftwarefdn/weaviate/commit/059c06685b644210132266876e57236fc3480f1d

**Comment by idcrosby** [comment]
resolved: https://github.com/creativesoftwarefdn/weaviate/pull/572
