### ISSUE TITLE
Dropping 'things' or 'actions' from the filter.

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#565]
In the [section on filters in the GraphQL documentation](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/graphql_local.md#filters), the paths of the filters are prefixed with  "things" and "actions".

This is superfluous information. The class names cannot overlap in any case.

Current query:
```graphql
 Get(where:{
      operator: And,
      operands: [{
        path: ["Things", "Animal", "age"],
        operator: LessThan
        valueInt: 5
      }, {
        path: ["Things", "Animal", "inZoo", "Zoo", "name"],
        operator: Equal,
        valueString: "London Zoo"
      }]
    }) { ... }
```

After removing the kind of class:
```graphql
 Get(where:{
      operator: And,
      operands: [{
        path: ["Animal", "age"],
        operator: LessThan
        valueInt: 5
      }, {
        path: ["Animal", "inZoo", "Zoo", "name"],
        operator: Equal,
        valueString: "London Zoo"
      }]
    }) { ... }
```

**Comment by bobvanluijt** [comment]
Agreed, please remove them.

@laura-ham can you please update this in the relevant docs.

**Comment by laura-ham** [comment]
Now I remember why the first element of the Path was "Things" or "Actions": because the path in the filter is the exact same path as you put in the graphql query from there. In the following example you see that the path in the filter is consistent with the query structure which follows.

```graphql
{
  Local {
    Get(where: { 
      path: ["Things", "City", "inCountry", "Country", "name"],
      operator:Equal,
      valueString: "Germany"
    }) {
      Things {
        City {
          name
          population
          InCountry {
            ... on Country {
              name
            }
          }	
        }	
      }
    }
  }
}
```

So, should we remove it or keep it like this?

**Comment by bobvanluijt** [comment]
Aha, good point. However, an `Animal` can _only_ be a thing.

**Comment by laura-ham** [comment]
I get the point, but why having the distinction between Things and Actions at all then in the API?

**Comment by moretea** [comment]
I believe that @bobvanluijt wants to distinguish between the two in the future. In any case, the class names of actions and things form one namespace; you cannot have a class `FooBar` that is both an Action and a Thing.

From a engineering perspective, they are identical at the moment.

**Comment by bobvanluijt** [comment]
What @moretea writes is correct, currently they are identical from an engineering perspective but they will almost certainly deflect in the future.

**Comment by laura-ham** [comment]
So if I understand it correctly, you want to keep the distinction in the API, but want to remove the distinction in the `path` in the filter? That does not sound logical to me..

**Comment by moretea** [comment]
@bobvanluijt https://github.com/creativesoftwarefdn/weaviate/issues/565#issuecomment-440064570 is ambiguous to me. Are you talking about the distinction in the REST API, or have you changed your mind and want to have it back in the filters :)?

You agreed to remove this here https://github.com/creativesoftwarefdn/weaviate/issues/565#issuecomment-438348996,  and I have implemented this last week. Do you these to be put back in? If so, I'll open another issue for that to keep track of it.

**Comment by bobvanluijt** [comment]
Aha, okay, I did not know this. I was talking about the filters and my response was based on @laura-ham's comment which she responded to later.

@laura-ham and @JeroenStravers1, can you confirm that this implementation that @moretea states above is reflected in the prototype and tests?

**Comment by laura-ham** [comment]
@bobvanluijt, I did not take any action regarding this because the discussion was not closed yet. So the implementation by @moretea is not yet reflected in the prototype, docs and tests.

**Comment by bobvanluijt** [comment]
Check @laura-ham 👍 
Can you please align with @moretea's implementation?

**Comment by laura-ham** [comment]
Of course, but I think we should make a decision about this issue, whether to keep the path as it is or not?

**Comment by bobvanluijt** [comment]
Concerning timelines and because @moretea already has implemented the above let's make a smart decision.

- @laura-ham do I understand correctly that you are _not_ in favor of removing them?
- @moretea how difficult would it be to revert and include them?

**Comment by bobvanluijt** [comment]
Ok, in that case we will leave it out for now and I'll close the issue.
