### ISSUE TITLE
valueDate is missing from the GraphQL filters

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#566]
Dates are one of the core primitive data types that are supported by Weaviate.

They are missing from the current GraphQL filters.

**Comment by moretea** [comment]
@laura-ham @bobvanluijt @JeroenStravers1, I'll add a `valueDate` field to the GraphQL API, not much work now that I'm building the resolvers.

**Comment by bobvanluijt** [comment]
Great point, thanks @moretea 

@laura-ham can you please add this to the relevant docs.

**Comment by laura-ham** [comment]
The reason that I didn't add this to the prototype is this: https://github.com/SeMI-network/weaviate-graphql-prototype/issues/30

The timestamp data format is not supported by graphql for javascript
So I could include a valueDate field, but can't set it to the right datatype so the test will fail if I set it to string for example..

**Comment by moretea** [comment]
I'm using strings, and parsing them in the resolver, see this snippet:

https://github.com/creativesoftwarefdn/weaviate/blob/90f5b0328fec0ebaac6eba9aca3bdc83e622c38c/graphqlapi/local/common_filters/filters.go#L348-L369

**Comment by laura-ham** [comment]
Okay thanks, I will add it to the prototype as string as well then
