### ISSUE TITLE
Behavior of 'not' in GraphQL filter

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#567]
From the [filter documentation](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/graphql_filters_local.md)

> If the operator is Not or NotEqual either the Operands or the Path and a ValueType must be filled.

Could we simplify this?

<h4>NotEqual</h4>

What about `NotEqual ` as a shorthand for `Not(Equal)`

  Or shown in examples:

```javascript
{ operator: "NotEqual", path: ["Car", "color"], valueString: "white" }
```
would be a shortcut for

```javascript
{ operator: "Not", operands: [ {operator: "Equal", path: ["Car", "color"], valueString: "white" } ] }
```

<h4>Not</h4>
I'd make  Not into a Not/None operator. 

In a simpler notation than the GrahpQL filters for clarity:
```
not: [ Car.color == white, Car.color == green]
```

would be logically equivalent to:

```
and: [ Car.color != white, Car.color != green]
```

**Comment by bobvanluijt** [comment]
Agreed from my side.

@laura-ham can you please update the [docs](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/graphql_filters_local.md) to reflect this.

**Comment by laura-ham** [comment]
@moretea I'm not sure what you mean, I think it already works like this?

**Comment by moretea** [comment]
I'd not overload the `Not` to work on both a list of operands, and a path/valuetype but keep it simple by only making it work on operands. 

I would propose to make the behavior of `And`, `Or`, and `Not` simllar.

Just like that all the `(Not)Equal` `Greater(OrEqual)Than` operators would work only values.

I guess that the intention was to have a `Not(Door.isOpen)`, but that makes the handling & error reporting harder than using `Equal(Door,isOpen, valueBool: false)`

**Comment by laura-ham** [comment]
Okay thanks. Implemented it like the following:
- `Not` should always be an operator followed by operands, which kind of acts on the same level as `And` and `Or`
- `NotEqual` should be followed by a value to be compared

So these two queries will result in the same:

```graphql 
{
  Local{
    Get(where: {
      operator:Not,
      operands: [{
        path: ["Things", "City", "name"],
        operator: Equal,
        valueString: "Berlin"
      }]
    }) {
      Things{
        City{
          name
        }
      }
    }
  }
}
```

``` graphql
{
  Local{
    Get(where: {
      path: ["Things", "City", "name"],
      operator: NotEqual,
      valueString: "Berlin"
    }) {
      Things{
        City{
          name
        }
      }
    }
  }
}
```

Hopefully this is what you meant @moretea?

**Comment by moretea** [comment]
Yep, indeed!
