### ISSUE TITLE
Add PercentageFalse and TotalFalse fields to Boolean properties of GetMeta Things/Actions

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#568]
We currently only allow insight into how many true values there are for a property of a class (absolute and relative), but as a user I'd be just as likely to be interested in false values. We should add these options to the Prototype and Weaviate.

**Comment by bobvanluijt** [comment]
Good idea @JeroenStravers1, can you suggest a syntax or add an example please?

**Comment by JeroenStravers1** [comment]
These fields would mirror the existing totalTrue and percentageTrue properties for Boolean Thing/Action properties in a GetMeta query. The proposed options would look like this next to the current options:
```graphql
Things {                        # or Actions
  SomeThing {
    booleanProperty {
      type
      count
      totalTrue
      percentageTrue
      totalFalse                # new, type Int.
      percentageFalse           # new, type Float.
    }
  }
}

**Comment by JeroenStravers1** [comment]
@laura-ham I just implemented this in Weaviate, I'll leave this issue open until it's also in the prototype

**Comment by JeroenStravers1** [comment]
Code was merged with develop
