### ISSUE TITLE
How to set custom contextionary or other config?

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#574]
Inside the Dockerfile, Weaviate runs with the following config:

1. [As set here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/Dockerfile#L62) with `--port` and `--scheme`. **Question**: How to change these settings while running the Docker as described [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/running-with-Docker.md).
2. [This configuration is used](https://github.com/creativesoftwarefdn/weaviate/blob/develop/tools/dev/config.json#L61) which [loads this](https://github.com/creativesoftwarefdn/weaviate/blob/develop/tools/dev/config.json#L73) contextionary. **Question**: How can somebody point to a different contextionary when running the Docker container as describeded [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/running-with-Docker.md).

**Comment by idcrosby** [comment]
@bobvanluijt just to confirm this is only for developers correct?

**Comment by bobvanluijt** [comment]
Correct

**Comment by idcrosby** [comment]
@bobvanluijt the above commit solves the first part.

Regarding the second part (contextionaries) if I understand it correctly there is a sample contextionary text file [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/test/contextionary/en_test-vectors-small.txt.bz2) which then gets 'built' into the required `idx` and `kdn` files. For the development workflow the simplest solution would seem to be adding an argument to the (generate contextionary script)[https://github.com/creativesoftwarefdn/weaviate/blob/develop/test/contextionary/gen_simple_contextionary.sh] so devs can point to their own file.

@moretea do you have some thoughts on this?

**Comment by moretea** [comment]
It is a _trained_ dataset. Not a list of words :)
So no generation during runtime; for big contextionary this takes ages. The idx and knn files are more a distrubition format.

We considered to make this just one file, but Spotify's libarary that we use for the k-nearest neighbour search uses the file length for it's indexing computations. We either had to use two files, or re-implement that library completely.

The `.idx` and `.knn` files are a bit like the `bzimage` and `rootfs` in the old days of linux booting. You need both to get started.

**Comment by bobvanluijt** [comment]
It is a bit different @idcrosby. 

Your observation is correct, but there will be different contextionaries.

The default contextionaries will be available on the web;
- `https://contextionary.creativesoftwarefdn.org/latest/contextionary.idx`
- `https://contextionary.creativesoftwarefdn.org/latest/contextionary.knn`
_Note: not available yet & Soon we will also be getting other files that are part of the contextionary_

So, end users need to be able to set a _custom location_ for contextionaries. Ideally this is a file-path _or_ URL.

**Comment by idcrosby** [comment]
Ok thanks @bobvanluijt that makes things a bit simpler.

**Comment by idcrosby** [comment]
@bobvanluijt I think the best way to handle contextionaries (after discussion with @moretea) is to add the contextionary files during build time.  Currently the code (weaviate) expects these files locally on the file system.  This way we won't need to modify weavaite at all.

**Comment by bobvanluijt** [comment]
That is perfectly fine with me @idcrosby. It is important to bear in mind though, that this means that people need to rebuild if they want to use a _different_ contextionary.

Is the following flow an option? (also asking for the docs);
- Use doesn't set any build arguments, the [latest version](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/contribute/contextionary.md#example-of-downloading-latest-vocabulary) is used.
- If a user sets: `--build-arg CONTEXTIONARY_LOC=./somedir` or `--build-arg CONTEXTIONARY_LOC=https://someurl.com/somedir` it respectively load from disk _or_ download the contextionary.
- We can always assume the same location for the -currently- three individual files as mentioned [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/contribute/contextionary.md#download).

**Comment by idcrosby** [comment]
https://github.com/creativesoftwarefdn/weaviate/commit/2cdb803a54ce75cc8980850609f35d17ecd0da21

**Comment by idcrosby** [comment]
https://github.com/creativesoftwarefdn/weaviate/pull/667

**Comment by idcrosby** [comment]
resolved via above PR
