### ISSUE TITLE
Validate how values are validated against the Contextionary

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#575]
After some tests were done by @etiennedi. I would like to validate the following. In case validated I will also add it to the contribution docs.

@moretea can you please validate the below and share what your findings are?

1. The contextionary is _case insensitive_. For example, the word `kyle` and `Kyle` will both have the same vector values.
2. Adding classes, properties, and keywords via the end-points should only have the _first character being case insensitive_. For example, the class: `Kyle` should automatically format to: `Kyle` even if it is added as `kyle`. The class: `kyleElaborate` formats to: `KyleElaborate` where the contextionary handles this class as two words ([thats's the reason for CamelCase](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/ontology-schema.md#camelcase)).

**Comment by etiennedi** [comment]
Background: This is how I discovered this:

- Goal: I wanted to create `Things` with only primitive properties
- I used any word from the contextionary to create such a primitive property. 
- If the word I wanted to use as a property name was capitalized in the contextionary, I converted the first character to lowercase
- this led to some successful creation of `Things`, others failed.
- When inspecting the failed ones, there were errors like this
  ```
   {"error":[{"message":"Could not find the word \'kyle\' from the property \'kyle\' in the class name \'Elaborate\' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
   ```
- `Kyle` is part of the contextionary, but `kyle` is not.
- To verify that this is an issue, I implemented a filter to only use words from the contextionary which were already lowercased to create properties. -> No more issues

**Comment by moretea** [comment]
The contextionary is case insenstive as far as everything is converted to lowercase during the checks.

We could prevent these kind of issues by improving the quality of the contextionary.

To mind comes adding a pre-processing step to make the corpus lowercase and remove stuff like interpunction by removing all characters that are not in the alphabet.

**Comment by moretea** [comment]
And yes, the camel cased words are split, and each of them is considered to be part of the input to compute the vector that represents the class / property.

**Comment by bobvanluijt** [comment]
I'm not sure I understand @moretea. 

You write that the contextionary is case insensitive. But also suggest pre-processing the corpus. I get this from an interpunction perspective but not from a word perspective. Like the example given by @etiennedi, it should have recognized "kyle" because it is in the contextionary with a capital K especially if the contextionary is case insensitive.

**Comment by etiennedi** [comment]
I'm not sure if it's due to capitalization or if there is another issue. A random test I just did with 100 random words from the contextionary led to only 79% success rate.

Granted some of those words are actually not suited to be classnames (like all-uppercase acronyms), but most words are contained in the contextionary, yet I'm seeing an error. I randomly spotchecked some (`Airbus`, `Tampa`, `Nader`) and found them all in the contextionary text file, yet weaviate is not allowing them

```
------------
Success: 79
Failed: 21
Success Rate: 79 %

Only the failures:
Could not submit thingClass Scottish to weaviate (Status 422): {"error":[{"message":"Could not find the word 'scottish' from the class name 'Scottish' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass III to weaviate (Status 422): {"error":[{"message":"'III' is not a valid class name"}]}
Could not submit thingClass Johnny to weaviate (Status 422): {"error":[{"message":"Could not find the word 'johnny' from the class name 'Johnny' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Gary to weaviate (Status 422): {"error":[{"message":"Could not find the word 'gary' from the class name 'Gary' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Barry to weaviate (Status 422): {"error":[{"message":"Could not find the word 'barry' from the class name 'Barry' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Sweden to weaviate (Status 422): {"error":[{"message":"Could not find the word 'sweden' from the class name 'Sweden' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass LGBT to weaviate (Status 422): {"error":[{"message":"'LGBT' is not a valid class name"}]}
Could not submit thingClass NASA to weaviate (Status 422): {"error":[{"message":"'NASA' is not a valid class name"}]}
Could not submit thingClass Soviets to weaviate (Status 422): {"error":[{"message":"Could not find the word 'soviets' from the class name 'Soviets' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Commissioner to weaviate (Status 422): {"error":[{"message":"Could not find the word 'commissioner' from the class name 'Commissioner' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Everton to weaviate (Status 422): {"error":[{"message":"Could not find the word 'everton' from the class name 'Everton' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Utah to weaviate (Status 422): {"error":[{"message":"Could not find the word 'utah' from the class name 'Utah' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Pittsburgh to weaviate (Status 422): {"error":[{"message":"Could not find the word 'pittsburgh' from the class name 'Pittsburgh' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Morris to weaviate (Status 422): {"error":[{"message":"Could not find the word 'morris' from the class name 'Morris' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Macedonia to weaviate (Status 422): {"error":[{"message":"Could not find the word 'macedonia' from the class name 'Macedonia' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Airbus to weaviate (Status 422): {"error":[{"message":"Could not find the word 'airbus' from the class name 'Airbus' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Nader to weaviate (Status 422): {"error":[{"message":"Could not find the word 'nader' from the class name 'Nader' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Coventry to weaviate (Status 422): {"error":[{"message":"Could not find the word 'coventry' from the class name 'Coventry' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Ka to weaviate (Status 422): {"error":[{"message":"Could not find the word 'ka' from the class name 'Ka' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Tampa to weaviate (Status 422): {"error":[{"message":"Could not find the word 'tampa' from the class name 'Tampa' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingClass Suwon to weaviate (Status 422): {"error":[{"message":"Could not find the word 'suwon' from the class name 'Suwon' in the contextionary. Consider using keywords to define the semantic meaning of this class."}]}
Could not submit thingVertex of type Scottish to weaviate (Status 422): {"error":[{"message":"no such class with name 'Scottish' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type III to weaviate (Status 422): {"error":[{"message":"no such class with name 'III' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type LGBT to weaviate (Status 422): {"error":[{"message":"no such class with name 'LGBT' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type Pittsburgh to weaviate (Status 422): {"error":[{"message":"no such class with name 'Pittsburgh' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type Morris to weaviate (Status 422): {"error":[{"message":"no such class with name 'Morris' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type Morris to weaviate (Status 422): {"error":[{"message":"no such class with name 'Morris' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type Nader to weaviate (Status 422): {"error":[{"message":"no such class with name 'Nader' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type Tampa to weaviate (Status 422): {"error":[{"message":"no such class with name 'Tampa' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type Tampa to weaviate (Status 422): {"error":[{"message":"no such class with name 'Tampa' found in the schema. Check your schema files for which classes are available"}]}
Could not submit thingVertex of type Suwon to weaviate (Status 422): {"error":[{"message":"no such class with name 'Suwon' found in the schema. Check your schema files for which classes are available"}]}
```

**Comment by moretea** [comment]
That is because I added a validation step to ensure that all words must be `CamelCased` for classes, and `camelCased` like that for properties.

Hence my suggestion to improve the contextionary; we discussed this in July and decided that given that the corpus was not 100% set in stone yet, we'd do this later. I can't find an issue about this unfortunately.

**Comment by moretea** [comment]
Note that simply changing the generator of the contextionary files is not sufficient; we might have a `Foobar` and `foobar` in there with different vectors. This complictes stuff as you can't remove elements from the contextionary.

I think that sanitizing the input would be the easiest to not allow nonsense input.

**Comment by etiennedi** [comment]
> That is because I added a validation step to ensure that all words must be CamelCased for classes, and camelCased like that for properties.

Don't think this applies to my example above. The words `Airbus`, `Tampa`, `Nader` are all `CamelCased`. Both in my request as well as in the contextionary. The only `camelCased` variant is in the error message itself, e.g.: `Could not find the word 'airbus' from the class name 'Airbus' in the contextionary. Consider using keywords to define the semantic meaning of this class.`.

**Comment by moretea** [comment]
For those examples, it is probably the case that only the word 'Airbus' is
actually added in the contextionary's wordlist

With a capital a.

The validation logic in the database scheme downcases all words after they
are validates / split into parts.

So, if no 'airbus' is available in the contextionary, the check fails and
claims that Airbus is not in the contextionary.

So if we implement preprocessing of the corpus before it is trained, these
issues disappear.

Op zo 18 nov. 2018 19:04 schreef Etienne Dilocker <notifications@github.com:

**Comment by bobvanluijt** [comment]
Thanks for this @moretea. Can you please define _what_ the preprocessing needs to do? I'll make sure that a new contextionary is rendered _including_ the preprocessing and based on the latest Wiki.

**Comment by moretea** [comment]
1. **Remove irrelevant characters** like interpunction. If you'd check the output, you'll note that it contains numbers, exclamation marks, percentages, etc.
2. **Normalize names** downcase the whole corpus

**Comment by moretea** [comment]
Note that this will not prevent us from having words in the contextionary  like personal names, eg "Bob". You probably don't want to have an action "EmailBob" to be automatically have a semantic meaning, but well, that's machine learning ;).

I imagine that we can restrict the words to the words that are in a processed dictionary, but still use the corpus to compute the distance. So the dictionary would be a 'filter' on the words to add to a contextionary.

Or even more fancy option, to automatically fiddle with the relative importance of words based on the kind of word (e.g. the noun `Email` is more descriptive than `Bob` in the `EmailBob` example).

This would actually fit in with the idea to only allow actions to start with verbs, and only allow things to be composed of nouns, or some rule like that.

**Comment by bobvanluijt** [comment]
In the contextionary @moretea. Practically this means;
1. I'll make sure that the vector file used to generate the contextionary _only_ contains `/[^a-z0-9]+/g` _and_ interpunction.
2. When creating things, actions, keywords, etc. You can ignore the interpunction in Weaviate.

What is _really_ important though is that;
1. Weaviate is in charge of CamelCase usage. If the word `elephant` is in the contextionary, and the thing `Elephant` is created (it needs to have a capital because it is a class) Weaviate should search for `elephant` in the contextionary. Or;
2. When a property is created called `locatedIn`. The validation in the contextionary should happen for the words `located` _and_ the word `in`.

**Comment by moretea** [comment]
That is exactly how it works yes.
