### ISSUE TITLE
Build/Push docker images from Travis

### ISSUE THREAD

**Issue by idcrosby** [creativesoftwarefdn/weaviate#580]
The CI system (Travis) should be building docker images for master and develop branches and push them to the Docker Hub repo (https://hub.docker.com/r/creativesoftwarefdn/weaviate/)

**Comment by moretea** [comment]
1 million :+1:'s

**Comment by bobvanluijt** [comment]
I can pick this up @idcrosby.

**Comment by idcrosby** [comment]
Docker commands

Build Development:
```
docker build -t creativesoftwarefdn/weaviate:unstable --target development .
```
Push Development:
```
docker push creativesoftwarefdn/weaviate:unstable
```

Build Master:
```
docker build -t creativesoftwarefdn/weaviate:$NEWVERSION --target weaviate_base .
```
Push Master:
```
docker push creativesoftwarefdn/weaviate:$NEWVERSION
```

**Comment by bobvanluijt** [comment]
Done
