### ISSUE TITLE
Get rid of docker-compose-test.yaml

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#581]
I noticed in #579 that we're using the `docker-compose-test.yaml` file for the acceptance tests.

There is no logical difference between these environments now, given that the schema is _in_ Weaviate now, and not in external files.

Also we should rething the configuration as suggested in #450

**Comment by bobvanluijt** [comment]
We need to stay aware that there can be different configurations especially when we create new connectors in the future.

I'm thinking of ditching the whole configuration file and add them as `--args` with specific defaults. Any thoughts on that @moretea and @etiennedi?

**Comment by moretea** [comment]
Agreed! But that concern is orthogonal to this issue that I opened.

Before #468 we needed two different compose files, because the schema was part of the configuration.

So this issue proposes to reduce complexity that is not needed.

**Comment by bobvanluijt** [comment]
Became obsolete, partly resolved, partly in other issues.
