### ISSUE TITLE
Apply HTTP endpoint batching implementation to GQL batching endpoint

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#584]
The HTTP endpoints use `/batching/things` and `/batching/actions`, where the GQL endpoint uses `/graphql/batch`. The HTTP endpoints also contain a solution for batched request error handling. Apply the HTTP approach to the GQL batching endpoint.

**Comment by bobvanluijt** [comment]
@JeroenStravers1 FYI: graphql batching is based on [Apollo GraphQL](https://www.apollographql.com/). We need to follow that implementation. This is not the case for the other endpoints.

**Comment by JeroenStravers1** [comment]
Batching endpoints are implemented and documented as discussed. Closing this issue.
