### ISSUE TITLE
Always get Contextionary from contextionary.creativesoftwarefdn.org

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#595]
1. Contextionaries should be downloaded from https://contextionary.creativesoftwarefdn.org/. More information [in the docs](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/contribute/contextionary.md#download)
2. By default, always the latest version should be downloaded (see the [example here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/contribute/contextionary.md#example-of-downloading-latest-vocabulary)).
3. There should be a configuration flag / setting where users can change the version number. This is always a semver number.
4. Also for dev and testing purposes ⬆️should be used.

**Comment by bobvanluijt** [comment]
cc: @etiennedi note [this](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/contribute/contextionary.md#example-of-downloading-latest-vocabulary) example.

**Comment by idcrosby** [comment]
https://github.com/creativesoftwarefdn/weaviate/pull/667

**Comment by idcrosby** [comment]
resolved via above PR
