### ISSUE TITLE
Inconsistency in property naming in GQL Get / GetMeta

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#596]
#### Get
Titleizes the name of references.

```graphql
{ 
  Local {
    Get  {
      Things {
        Airport {
          InCity {
            __typename
          }
        }
      }
    }
  }
}
```

#### GetMeta
Does not titleize reference names
```graphql

{
  Local {
    GetMeta {
      Things {
        City {
           inCountry { ...   }
        }
      }
    }
}
```

#### Suggested solution
Also titleize the references in the `GetMeta` requests.

**Comment by bobvanluijt** [comment]
@laura-ham and @JeroenStravers1 can you please pick this up asap?

**Comment by JeroenStravers1** [comment]
Sure, I can pick this up as soon as the refactoring is complete.

**Comment by JeroenStravers1** [comment]
This is no longer an issue
