### ISSUE TITLE
Improve foobar connector (and update none used functions)

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#597]
Remove the functions;
- `func (j *Janusgraph) DeleteAction()`
- `func (j *Janusgraph) HistoryAction()`
- `func (j *Janusgraph) MoveToHistoryAction()`
- `func (f *Janusgraph) GetGraph()`
- `func (j *Janusgraph) DeleteThing()`
- `func (j *Janusgraph) HistoryThing()`
- `func (j *Janusgraph) MoveToHistoryThing()`

**IN:**
- https://github.com/creativesoftwarefdn/weaviate/tree/develop/database/connectors

**Comment by moretea** [comment]
I would suggest to not remove DeleteAction and DeleteThing. I asume we still want to be able to remove data?

These functions _are_ implemented, see
https://github.com/creativesoftwarefdn/weaviate/blob/develop/database/connectors/janusgraph/things.go#L88

which uses this helper function: https://github.com/creativesoftwarefdn/weaviate/blob/develop/database/connectors/janusgraph/helper.go#L580-L588

I don't know what the purpose of GetGraph is.

And yes, I'd say that the History things should be removd for now.

**Comment by bobvanluijt** [comment]
Thanks @moretea. 

Note to self: also update docs.
