### ISSUE TITLE
Add to docs how to set none-standard Contextionary location

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#608]
Related to: https://github.com/creativesoftwarefdn/weaviate/issues/574

Add to [this](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/running-with-Docker.md) file how to change to another Contextionary.

**Comment by idcrosby** [comment]
https://github.com/creativesoftwarefdn/weaviate/pull/672
