### ISSUE TITLE
Schema acceptance test currently not comparing field content length

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#636]
## Background
The [schema acceptance test](https://github.com/creativesoftwarefdn/weaviate/blob/develop/test/acceptance/graphql_schema_test.go) launches an introspection query at Weaviate and the prototype and compares all elements in the result. It also checks whether `map` and `array` fields contain the same amount of elements. This test assumes both Weaviate and the prototype contain the [test schema](https://github.com/creativesoftwarefdn/weaviate/tree/develop/test/schema), which contains two `Things` and two `Actions`.

## Issue
The current acceptance test suite as run by [Travis](https://github.com/creativesoftwarefdn/weaviate/blob/develop/.travis.yml) fills the Weaviate instance with both the test schema and [an additional schema](https://github.com/creativesoftwarefdn/weaviate/tree/develop/test/acceptance/graphql_resolvers_local/fixtures). This causes the schema test to fail; the Weaviate now contains four `Actions` and nine `Things`, instead of the two/two the test is expecting.

## Current State
The length comparisons in the acceptance test are hidden behind a [boolean](https://github.com/creativesoftwarefdn/weaviate/blob/2e0284add983344bba6632078a3c13a1e6ee805b/test/acceptance/graphql_schema_test.go#L29). This is a hotfix, this issue was blocking a merge of a substantial amount of code.

## Proposed solution
- Clean up the Weaviate's schema in between tests
- Other?

**Comment by etiennedi** [comment]
I agree on the proposed solution: In more detail, each test should insert the data it needs before the "suite", then run all of its tests and eventually clean up everything that they touched upon.

Let's please wait with this until #602 is finished though. I'm currently writing acceptance tests there and already have to refactor quite a bit of the existing tests. If we try to change this at the same time, we'd have guaranteed merge conflicts that wouldn't be to easy to resolve ;).

**Comment by bobvanluijt** [comment]
Sounds good to me.

**Comment by JeroenStravers1** [comment]
Closing gh-636 as we're no longer using the schema acceptance test
