### ISSUE TITLE
Update Network Cross-Ref API design

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#661]
As outlined in #413, we want to take some shortcuts to make #660 easier.

Namely we want to use something like 
```graphql
... on WeaviateB__Instrument {
  name
}
```

However, we believe the best API design right now (cc @laura-ham) would be along the lines of
```graphql
... on WeaviateB {
  Instrument {
    name
  }
}
```

Since the latter deviates (one more level) from the current recursive resolving we're already doing for local cross-refs, we want to skip this (more nested) design in #660 (in order to move faster) and then clean it up as part of this issue.

**Comment by etiennedi** [comment]
Update: The original statement might no longer be true. I'm out of office today, so I'll give some more detailed reasoning later. In short the `WeaviateB__Instrument` might actually be the preferred way because of easier to handle responses. (For details those of you with access to the SeMI slack channel can see my most recent video in the general channel).

I'll also update here in more detail at a later point.

**Comment by bobvanluijt** [comment]
Curious to know what the status is here @etiennedi

**Comment by etiennedi** [comment]
This one has become obsolete. We thought at first that the proposal above would make it easier to use, but in fact that's not the case. The general feedback (on Slack) was that the version we already have is not just sufficient, but in fact preferred. Therefore closing and not changing anything.

**Comment by bobvanluijt** [comment]
check
