### ISSUE TITLE
docker-compose up panics after import

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#663]
Since CI only uses the `docker-compose-test.yml` it seems we managed to break the `docker-compose.yml` with one of the recent PRs.

We should fix it and also consider if we really need two separate docker-compose files. Maybe they can be combined into one.

## How to reproduce

1. Run `docker-compose up`
2. Wait for the importer to finish
3. Try running a graphql query, it'll fail

## Possible reasons
Could be that some of the recent network features require something that's not present in the setup?

**Comment by bobvanluijt** [comment]
What does "import" mean in this context?

**Comment by etiennedi** [comment]
Running the importer script which imports the demo schema and vertices. 

I think this issue can be closed though. I tried to reproduce it yesterday towards EOD and noticed that I simply had an old (cached) weaviate container. After rebuilding it all was fine. So most likely after some more investigation we'll find out this was just user error and not an actual bug.

**Comment by bobvanluijt** [comment]
Ok, I'll close it @etiennedi. 

Reason for asking was that I want to move importing to the CLI tool asap.

**Comment by etiennedi** [comment]
@bobvanluijt do we have an issue for that yet? What's the overall strategy for **how** the cli tool should handle importing. My thoughts are:

* Importing is non-trivial because of local cross-refs. You can't cross-ref something that isn't there, so that's why currently both the go-import script as well as the nodejs verification script first import every thing/action class without properties. Then adds them via `PATCH` once we can be sure all local classes are in. I don't think we should rebuild this logic a third time in python, so I'd be in favor of reusing the (dockerized) importer script, however...
* ... the current importer script is not production quaility and should not be given to customers in the current form. For example it doesn't have the same API on weaviate, panics on errors with cryptic messages, etc. Having said that, I think we could get this to production quality within a day or two.
