### ISSUE TITLE
replace custom logger with something more standard

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#666]
We seem to be using some custom made logger `messages.Messaging`. This logger is not very powerful and there's no need to build a custom logger. We could easily use something like [sirupsen/logrus](https://github.com/sirupsen/logrus).

## Advantages from switching
* A standard interface that makes developing easier
* Ability to configure logger, for example if we need structured logging (very typical on Kubernetes), we can simply turn it on with one command.
* Properly formatted logs will be much easier to read, both for ourselves, but also for our users when running in the cloud

**Comment by idcrosby** [comment]
@etiennedi structured and consistent logging is the most important. Log aggregation is something you add on top of k8s, so you need to support multiple tools. 

Custom fields, such as the example you mention, which should appear on all logs can be added as metadata in the kubernetes manifests. Most log aggregation tools can correlate this data to the actual logs.
