### ISSUE TITLE
Missing GraphQL typename for classes

### ISSUE THREAD

**Issue by dljcollette** [creativesoftwarefdn/weaviate#670]
In order to cache data in Playground, I need to fetch the class GraphQL property `__typename`. The classes in the test data do not contain a typename, which makes it impossible to cache data on the client.

```
query Test {
  Local {
    Get {
      Actions {
        Flight {
          __typename
        }
      }
    }
  }
}
```
I would like this to return a typename, just like the GraphQL prototype does:
```
{
  "data": {
    "Local": {
      "Get": {
        "Actions": {
          "Flight": [
            {
              "__typename": "Flight"
            }
          ]
        }
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
Hi @dljcollette,

quick question: Is this available on the Prototype, but missing from Weaviate? Because if so, I'll treat it as a bug and can fix it right away. 

If it's not available on the prototype either, it would be an API change, that I'd like to go over with @laura-ham first.

**Comment by dljcollette** [comment]
@etiennedi, this is available in the prototype right now and afaik build in GraphQL by default, so I would  treat it as a bug.

**Comment by etiennedi** [comment]
Ok, perfect. In which places do you need it? Only in `Local -> Get -> <Kind> -> <ClassName>` or also in other places?

**Comment by dljcollette** [comment]
In addition to the above query, GraphQL by default exposes `__typename` not only on <ClassName> but on every GraphQL type.

**Comment by etiennedi** [comment]
Are you sure? It sounds from the docs as if it was only exposed on queries that have an **uncertain** return type: https://graphql.org/learn/queries/#meta-fields

**Comment by dljcollette** [comment]
> GraphQL allows you to request __typename, a meta field, at any point in a query to get the name of the object type at that point.

This docs say so.

**Comment by dljcollette** [comment]
Yes, indeed. Also, I have never exposed `__typename` by hand in either the Facebook and Apollo implementations and it always worked.

**Comment by etiennedi** [comment]
@dljcollette I just verified and I don't think I can reproduce the issue. It seems as if `__typename` is working fine. This is what I'm currently getting back, is this not the intended result?
![image](https://user-images.githubusercontent.com/8974479/53724813-09e5f900-3e6b-11e9-8303-79e17b8b9ac0.png)

**Comment by dljcollette** [comment]
@etiennedi I can't reproduce the original issue either. Should have also taken a screenshot :relaxed: However, the issue still exist in other GraphQL types, for example: ![schermafdruk 2019-03-04 11 28 44](https://user-images.githubusercontent.com/1950288/53727525-c0001180-3e70-11e9-9a22-919b3a3ca922.png)

**Comment by etiennedi** [comment]
Thanks for the example, I'll address this immediately. Can you please list all other places that it fails for you. I'll add a test for each one and fix it. But right now, I don't know which places require fixing and which don't.

**Comment by etiennedi** [comment]
Bugfix just pushed, added two new tests and also verified manually:
![image](https://user-images.githubusercontent.com/8974479/53730269-b75f0980-3e77-11e9-86ea-908ad89da364.png)

I'm keeping this issue open until we have verified whether it's OK everywhere now or fails in other places now.
