### ISSUE TITLE
Swap function and property level in Aggregation function around

### ISSUE THREAD

**Issue by laura-ham** [creativesoftwarefdn/weaviate#694]
See issue #693 for reasoning and details.

- [x] Prototype
- [x] Go implementation
- [x] Documentation

**Comment by etiennedi** [comment]
I'll do the changes in the go code as part of #693, already added it as a task item there. Nevertheless, still good to track it here as well, I'll make sure to tick off the box when I'm done.

**Comment by etiennedi** [comment]
Go implementation has been changed for both `Local { Aggregate }`, as well as `Network { Aggregate }`. The changes will be merged with the overall PR for #693 and can currently be found on the branch `feature/local_aggregate`:
<img width="820" alt="screenshot 2019-01-23 at 12 57 54" src="https://user-images.githubusercontent.com/8974479/51605800-61aa4f80-1f10-11e9-853f-1fb2bf64d121.png">
<img width="871" alt="screenshot 2019-01-23 at 11 26 45" src="https://user-images.githubusercontent.com/8974479/51605801-6242e600-1f10-11e9-8d87-4969780ba297.png">

**Comment by etiennedi** [comment]
@laura-ham I think we can close this or is anything still missing?

**Comment by laura-ham** [comment]
> @laura-ham I think we can close this or is anything still missing?

I think we can close it!
