### ISSUE TITLE
Lodash has a security vulnerability in the prototype

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#707]
See: https://github.com/creativesoftwarefdn/weaviate/network/alerts

Probably updating to the latest version is enough.

**Comment by laura-ham** [comment]
@bobvanluijt for me this link leads to a 404 page..

**Comment by bobvanluijt** [comment]
@laura-ham [this dep has a vulnerability](https://github.com/creativesoftwarefdn/weaviate/blob/develop/graphqlapi/prototype/package.json#L19) and should be updated to the latest version.

**Comment by laura-ham** [comment]
@bobvanluijt I updated the lodash (and other packages) to the latest version. Since I could not see where the security vulnerability came from, I can't check if this is resolved now. I assume so, but can you confirm this in close this issue accordingly?

**Comment by bobvanluijt** [comment]
@laura-ham yes, it is resolved!

<img width="767" alt="screenshot 2019-02-16 at 12 36 03" src="https://user-images.githubusercontent.com/5509162/52899176-73b5a000-31e7-11e9-928c-97726c630178.png">
