### ISSUE TITLE
Count number of calls to the API

### ISSUE THREAD

**Issue by rafaelcanalesduron** [creativesoftwarefdn/weaviate#708]
There is a feature in the playground where we need will count the number of calls to the API per interaction and show them. Is this something that will be built into the API?
@etiennedi @laura-ham @bobvanluijt
https://github.com/SeMI-network/playground/issues/60

**Comment by etiennedi** [comment]
Hi @rafaelcanalesduron, 

I think I need a bit more context here, I don't quite understand what the feature request is yet.

From what I understand from the linked issue, a playground "interaction" can be made up of multiple API calls. The user should be made aware how many where required. If that's the case I think the only party that could actually count the calls would be the playground itself as the one coordinating these multiple API calls.

Please correct me if I misunderstand something about this feature (request).

**Comment by rafaelcanalesduron** [comment]
What we are assuming is that providing users with the number of calls would give them an idea of how much they are consuming from the API (therefore an idea about costs). 

We haven't defined what an interaction in the playground in this context is yet. You're right, an interaction can be made up of multiple API calls. This is something that Dominique would know more about since he is using the API to build the playground. What do you think @dljcollette?

**Comment by bobvanluijt** [comment]
The goal is very straight forward. Every time a Playground is rendered (or the user changes something in the frontend), the UI does an x-amount of calls to the Weaviate API. Those ones we want to count. Adding this to the API would be the wrong way around because it can't know how much

**Comment by etiennedi** [comment]
Agree, the API is stateless and not aware of any sessions. Additionally there's no way of knowing from the backend whether an isolated call belongs to "UI Interaction 1" or "UI Interaction 2". So, this would only be possible client-side.

Closing this one, so you can take the discussion to the playground project. Feel free to reopen if I misunderstand anything and we do need an API-side implementation.
