### ISSUE TITLE
Telemetry error handling

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#737]
## Issue
I'm using a lib to encode function usage logs in [CBOR](http://cbor.io/) format before posting them to the monitoring endpoint. If this conversion fails for any reason (after retrying, etc), then what should happen to the unconverted logged records?

## Options
- Log them like we will log failed posts (but keep these separated)
- Something else?

@bobvanluijt @etiennedi

related: #699 #736

**Comment by bobvanluijt** [comment]
@etiennedi, you had a suggestion for storing, right? It is important to keep them _somewhere_ so that we can collect them later.

**Comment by etiennedi** [comment]
@JeroenStravers1 Was this issue opened before or after we talked about using `etcd` for storage if sending fails? Do we need a different solution or does this solution also apply here?

**Comment by JeroenStravers1** [comment]
Before, the same solution applies here. I'll put this info in etcd and document where it's stored. I'll close the issue once this is implemented.

**Comment by etiennedi** [comment]
Cool, I've removed the `help wanted` label :) Feel free to re-add it if you have other questions.

**Comment by etiennedi** [comment]
@JeroenStravers1 can this be closed?

**Comment by JeroenStravers1** [comment]
closing gh-737, added cbor conversion error logging
