### ISSUE TITLE
Weaviate own peer name optional

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#739]
## Issue
Weaviate instances do not currently need to have a peer-to-peer name if they're not part of a peer-to-peer network. However, each Weaviate instance needs to have a name for the monitoring service.

## Background
Weaviate instances will post logs of function calls to a monitoring endpoint. We need to be able to identify which log belongs to which instance, both to be able charge users and to perform (advanced) analytics.

## Solution
These conditions must be met if the monitoring service is to deliver usable data:
- Each Weaviate instance must have a name
- All Weaviate names must be unique to their network
- Other?

Thoughts @etiennedi @bobvanluijt ?

related: #699

**Comment by etiennedi** [comment]
Maybe this could also be separate names. The monitoring name is probably machine-read and could even be a uuid or some other cryptic identifier. The peerName (in the network section) however is used as the display name for this peer (in the GraphQL api for example). So there might be an advantage to keep them separate.

**Comment by bobvanluijt** [comment]
Ha, I did not know this (I assumed they all had names).

@JeroenStravers1, For now, I would suggest;
- if you have a name, set it.
- if you don't have a name, leave it blank.

**Comment by JeroenStravers1** [comment]
Fair enough, I assumed we need to use names as UUIDs but now realize we also have the sender's IP address. I'll implement it like that, thanks!
