### ISSUE TITLE
Cardinality not implemented in GraphQL

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#754]
Tested in version `0.12.60`, it seems that the cardinality is not implemented properly into GraphQL.

There are two ways to create a class:

## At most one

```bash
curl -X POST http://localhost:8080/weaviate/v1/schema/things/City/properties -H "Content-Type: application/json" -d '{
  "@dataType": [
    "Zoo"
  ],
  "cardinality": "atMostOne", # <=====
  "description": "...",
  "name": "hasZoo",
  "keywords": []
}'
```

## Many

```bash
curl -X POST http://localhost:8080/weaviate/v1/schema/things/City/properties -H "Content-Type: application/json" -d '{
  "@dataType": [
    "Zoo"
  ],
  "cardinality": "many", # <=====
  "description": "...",
  "name": "hasZoo",
  "keywords": []
}'
```

# Problem

From a GraphQL perspective, this should result in two different ways to query;

## At most one

```graphql
{
  Local {
    Get {
      Things {
        Zoo {
          name
          InCity{
              name
          }
        }
      }
    }
  }
}
```

## Many

```graphql
{
  Local {
    Get {
      Things {
        Zoo {
          name
          InCity{
            ... on City{
              name
            }
          }
        }
      }
    }
  }
}
```

Currently, both forms of the cardinality use the `many` structure to query the graph.

# Question

Was this by design or can this implementation be improved?
cc: @JeroenStravers1 @laura-ham @etiennedi

**Comment by etiennedi** [comment]
I wasn't aware of a separate version for `AtMostOne`. In fact I assumed aiming for a consistent return value in GraphQL would even prevent us from allowing something like the above?

If we were to implement the split as outlined above, we'd need to come up with a new design for Network Cross-Refs, because right now they rely on the `InlineFragments` to be available. For example

```graphql
 InCity{
            ... on WeaviateB__City{
              name
            }
``` 

Another option could also be to require cardinality to be set to `many` if Network Refs should be possible, then we could never run into a situation where we have the structure for "AtMostOne", but still need an `InlineFragment` for the remote peer.

**Comment by laura-ham** [comment]
I thought that crossreferences in `@datatype` always require your second way of querying, no matter the cardinality..? 

```graphql
InCity{
    ... on City{
        name
    }
}
```

**Comment by etiennedi** [comment]
> I thought that crossreferences in @datatype always require your second way of querying, no matter the cardinality..?

Thought so too, and that's also what the implementation looked like when I joined.

**Comment by bobvanluijt** [comment]
IMO it is a matter of UX.

If I work with an unknown Weaviate I need to always;
1. Determine what is a cref.
2. Determine which potential Classes are possible.
3. Write an `... on X` query.

If we have `atMostOne`, we could eliminate steps 2 and 3 because it is known which Class resolves into the cref-property.

**Comment by bobvanluijt** [comment]
Additionally to the above (and because I created: https://github.com/creativesoftwarefdn/weaviate/issues/756)

From a _data input_ perspective, the cardinality works as expected.

**For example for `many`:**

```bash
$ curl -X PATCH http://localhost:8080/weaviate/v1/things/3c6ac167-d7e5-4479-a726-8341b9113e40 -H "Content-Type: application/json" -d '[
  {
    "op": "add",
    "path": "/schema/hasAnimals",
    "value": [
      {
        "$cref": "weaviate://localhost/things/ac19c17b-63df-4d6f-9015-9086bb3466c4"
      },
      {
        "$cref": "weaviate://localhost/things/82f91e01-37b4-431c-98d1-43ebb48bca0f"
      }
    ]
  }
]'
```

**For example for `atMostOne`:**

```bash
$ curl -X PATCH http://localhost:8080/weaviate/v1/things/3c6ac167-d7e5-4479-a726-8341b9113e40 -H "Content-Type: application/json" -d '[
  {
    "op": "add",
    "path": "/schema/hasAnimals",
    "value": {
        "$cref": "weaviate://localhost/things/ac19c17b-63df-4d6f-9015-9086bb3466c4"
      }
  }
]'
```

# Recapitulation

To recap, I would expect the GraphQL interface to not ask me to define a class (`... on X`) when `atMostOne` is set.

**Comment by bobvanluijt** [comment]
Obsolete, has nothing to do with cardinality. Updated here: https://github.com/creativesoftwarefdn/weaviate/issues/757
