### ISSUE TITLE
Query with fragment on union fails

### ISSUE THREAD

**Issue by dljcollette** [creativesoftwarefdn/weaviate#761]
The following query is correct GraphQL syntax. However, is responds with an error as shown below the query. I was expecting a query response with `Animal` objects nested under `HasAnimals`. 

The query works when I remove the `localThingsAnimal` fragments and move those fields in `HasAnimals { ... on Animal { <fields> } }`. However, according to the GraphQL spec I should also be able to perform a query with fragments as shown below.
```
query SelectedClassesWithFilters {
  Local {
    ...localThingsZoo
  }
}

fragment localThingsAnimal on Animal {
  name
  species
  uuid
}

fragment localThingsZoo on WeaviateLocalObj {
  Get {
    Things {
      Zoo {
        name
        uuid
        HasAnimals {
          ...localThingsAnimal
        }
      }
    }
  }
}
```
Response:
```
{
  "data": {
    "Local": {
      "Get": {
        "Things": {
          "Zoo": null
        }
      }
    }
  },
  "errors": [
    {
      "locations": [
        {
          "column": 7,
          "line": 16
        }
      ],
      "message": "Expected a InlineFragment; you need to specify as which type you want to retrieve a reference &ast.FragmentSpread{Kind:\"FragmentSpread\", Loc:(*ast.Location)(0xc0001bc100), Name:(*ast.Name)(0xc0002a90e0), Directives:[]*ast.Directive{}}",
      "path": [
        "Local",
        "Get",
        "Things",
        "Zoo"
      ]
    }
  ]
}
```

**Comment by etiennedi** [comment]
I assume this has to do with how the resolver for `Local { Get }` extracts the subquery tree. It literally expects the fragment that represents the Schema Class on the level of `Has Animals`. 

It seems like that due to this issue we are currently not entirely conforming with everything that's possible in GraphQL. However, there's also extremely limited capacity on the MVP roadmap. Since there is a workaround (inlining), unfortunately I see no other option at the current point in time than to push this back to some later point. 

@bobvanluijt Since a user that tries to form a query the same way that @dljcollette formed it could run into the same issue, it might make sense to highlight this issue in the FAQ until it is fixed. (Which I predict with the current stack of open issues won't be too soon). The proritization of this can of course change if we see that this is a common pain point for users. At the moment, I'd predict that it's more of an edge-case. (I might very well be wrong about that, though).

**Comment by bobvanluijt** [comment]
Thanks for highlighting this @etiennedi.

@dljcollette, can you please share an example of the query above which is now parsed by Weaviate?

**Comment by dljcollette** [comment]
This is an inlined version that currently works in Weaviate:
```
query SelectedClassesWithFilters {
  Local {
    ...localThingsZoo
  }
}

fragment localThingsZoo on WeaviateLocalObj {
  Get {
    Things {
      Zoo {
        name
        uuid
        HasAnimals {
          ... on Animal {
            name
            species
            uuid
          }
        }
      }
    }
  }
}
```
Result: 
```
{
  "data": {
    "Local": {
      "Get": {
        "Things": {
          "Zoo": [
            {
              "HasAnimals": [
                {
                  "name": "Alphonso",
                  "species": "elephant",
                  "uuid": "361bf7d9-10e4-4689-bd04-c9cf881c6565"
                },
                {
                  "name": "Bert",
                  "species": "elephant",
                  "uuid": "629c6f91-f41c-4f53-968c-68605382dd5d"
                }
              ],
              "name": "Artis",
              "uuid": "475c0f64-f322-46ec-9082-d944531da6d2"
            },
            {
              "HasAnimals": null,
              "name": "The Berlin Zoological Garden",
              "uuid": "a95fcec8-796c-40c4-802a-0c8d90cebaa8"
            }
          ]
        }
      }
    }
  },
  "errors": null
}
```

**Comment by bobvanluijt** [comment]
Thanks

**Comment by dljcollette** [comment]
Here's an example of a query with depth:
```
query SelectedClassesWithFilters {
  Local {
    ...localThingsCity
  }
}

fragment localThingsAnimal on Animal {
  name
  species
  uuid
}

fragment localThingsCity on WeaviateLocalObj {
  Get {
    Things {
      City {
        name
        uuid
        HasZoo {
          ...localThingsZoo
        }
      }
    }
  }
}

fragment localThingsZoo on Zoo {
  name
  uuid
  HasAnimals {
    ...localThingsAnimal
  }
}
```

**Comment by etiennedi** [comment]
> Here's an example of a query with depth:

Thanks. Resolving this shouldn't be an issue if I can resolve it in general. The "nested" fragments would call the same resolver multiple times, so from the perspective of the resolver, there's really just a single level of new fragments.

I'm optimistic I can fix this rather quickly now. I'll keep you updated.

**Comment by etiennedi** [comment]
Currently blocked by https://github.com/graphql-go/graphql/issues/455

I'll see if I can come up with a workaround in the meantime, like using a regular expression to try and extract the Type.

**Comment by etiennedi** [comment]
@bobvanluijt Since I'm about to push a fix, there is no more need to mention this bug in the docs.

**Comment by etiennedi** [comment]
Closing as the workaround fixed the issue. Once a nicer solution becomes available in `graphql-go` we can always switch to this one.
