### ISSUE TITLE
Implement GQL function monitoring

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#769]
I'm implementing the code required to log function calls but cant implement the actual logging calls yet (pending an answer). Update these once the question is answered.

**Comment by bobvanluijt** [comment]
@JeroenStravers1 can you please make a reference to the outstanding question? This is currently to ambiguous.

**Comment by JeroenStravers1** [comment]
My bad, I was referring to a question I posed on Slack regarding the ServiceID document. The question has been answered, this is no longer an issue.
