### ISSUE TITLE
Telemetry: Add GQL/POST filtering to Register()

### ISSUE THREAD

**Issue by jeroenstraverskpn** [creativesoftwarefdn/weaviate#773]
## Issue:
When registering function usage currently the `RequestsLog`'s `Register()` doesn't discriminate between post types when deciding whether to create a new record or to update the `Amount` property of an existing record; it only looks at the serviceID. This means that a POST `Get` and a GQL `Get()` will be logged as the same record type.

## Solution:
Add Type filtering to `Register()`

**Comment by JeroenStravers1** [comment]
This issue has been resolved.
