### ISSUE TITLE
Proposal: Use yaml instead of json for weaviate configuration

### ISSUE THREAD

**Issue by etiennedi** [creativesoftwarefdn/weaviate#777]
Idea: Let's use `yaml` instead of `json` for the overall config.

Why?
* `yaml` is easier to edit for humans than `json`
* `yaml` allows comments. Especially with the configuration options that might be required for #720 I can really see additional value in comments
* In our helm chart the current config is a hard-coded `json` in `yaml`. If the configuration was yaml anyway, we might be able to simply this a bit.

@bobvanluijt @idcrosby @dljcollette @jeroenstraverskpn @laura-ham 
Interested to hear what you think :)

**Comment by bobvanluijt** [comment]
Yes, all for it. Let’s do it 👍

**Comment by laura-ham** [comment]
I'm convinced; it's easier and more applicable

**Comment by etiennedi** [comment]
Awesome. That was easy. Then again with this issue number this couldn't possibly have gone wrong.

**Comment by bobvanluijt** [comment]
Haha

**Comment by etiennedi** [comment]
I'm implementing this in an entirely non-breaking fashion in #720. `json` will still work, but `yaml` can also be used. This way we don't have to coordinate this with existing setups or the helm chart. Nevertheless we should update them soon as well.

Closing here in favor of #720.
