### ISSUE TITLE
Running the dev environment fails on Building genesis_fake

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#786]
Running the dev setup fails.

`./tools/dev/restart_dev_environment.sh` results in:

```bash
go: verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
	downloaded: h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=
	go.sum:     h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
```

On `Step 7/26 : RUN go mod download` in `Building genesis_fake`

**Comment by etiennedi** [comment]
@bobvanluijt Can you add some steps how to reproduce this please? Just running the script is working fine for me, as well.

**Comment by etiennedi** [comment]
I'm deleting my entire docker image and container cache now, to see if that changes anything.

**Comment by etiennedi** [comment]
Even without any cache whatsoever, it's building absolutely fine for me.

@bobvanluijt I can only imagine that you have an outdated or corrupted docker image locally that is creating an issue. Please do

1. Stop all running docker containers (e.g. with `docker rm -f $(docker ps -q)`
2. Delete all docker images with `docker rmi -f $(docker images -q)`

I'm willing to bet a nice bottle of wine that this will fix it 🤣

**Comment by bobvanluijt** [comment]
Haha, deal! Here we go...

**Comment by etiennedi** [comment]
Closing, as @bobvanluijt has confirmed via Slack that the above did indeed fix the problem.
