### ISSUE TITLE
Different body for thing and action POST and PUT

### ISSUE THREAD

**Issue by dljcollette** [creativesoftwarefdn/weaviate#823]
The structure of the request body for [adding a thing or action](https://app.swaggerhub.com/apis/bobvanluijt/weaviate/0.12.70#/actions/weaviate.actions.create) differs from the request body for [updating a thing or action](https://app.swaggerhub.com/apis/bobvanluijt/weaviate/0.12.70#/actions/weaviate.action.update)

POST:
```
{
  "action": {
    "@class": "string",
    "@context": "string",
    "schema": {}
  },
  "async": true
}
```

PUT:
```
{
  "@class": "string",
  "@context": "string",
  "schema": {},
  "creationTimeUnix": 0,
  "lastUpdateTimeUnix": 0
}
```
Though this is technically not a bug, from a UX perspective I would expect them to have the same structure - even if one has additional key-value pairs.

**Comment by dljcollette** [comment]
The same goes for the [validating a thing or action](https://app.swaggerhub.com/apis/bobvanluijt/weaviate/0.12.70#/actions/weaviate.actions.validate), which seems to be maintain the same body structure as with `updating a thing or action`, but not with `adding a thing or action`.

Validate POST:
```
{
  "@class": "string",
  "@context": "string",
  "schema": {}
}
```

**Comment by dljcollette** [comment]
Also, I've seen that the docs describe different request bodies compared to Swagger:

[PUT in docs](https://github.com/creativesoftwarefdn/weaviate/blob/master/docs/en/use/RESTful.md#update-a-action)
```
{
    "action": {
        "@class": "Animal",
        "@context": "http://myzoo.org",
        "schema": {
            "name": "Charles",
            "species": "monkey"
        }
    }
}
```

[POST validate in docs](https://github.com/creativesoftwarefdn/weaviate/blob/master/docs/en/use/RESTful.md#validate-a-action)
```
{
    "action": {
        "@class": "Animal",
        "@context": "http://myzoo.org",
        "schema": {
            "name": "Bert",
            "species": "elephant"
        }
    }
}
```

**Comment by etiennedi** [comment]
I've started addressing all of these in #826. I'll keep this issue open until #826 is ready to be merged.

**Comment by etiennedi** [comment]
Closing as #826 has been merged.
