### ISSUE TITLE
Telemetry acceptance test sometimes returns EOF error

### ISSUE THREAD

**Issue by JeroenStravers1** [creativesoftwarefdn/weaviate#829]
## Issue
The acceptance test for request logging is sometimes failing with an `EOF` error. @etiennedi increased the waiting time before querying the mock api and this seems to have resolved it locally, but this error is still occurring at the CI server. This error is currently blocking progress.

## Background
The acceptance test for request logging works by sending a request to the test weaviate, `sleeping` until the weaviate should have sent its logs to the telemetry endpoint (a mock api in this case), firing a `get` at the mock api, decoding the response body and then checking its structure. 

## Related
[gh-821](https://github.com/creativesoftwarefdn/weaviate/pull/821)

**Comment by JeroenStravers1** [comment]
After doing some research it appears to be a known issue. Adding 
`request.close()` 
right after 
`request, err := http.NewRequest(method, url, httpBody)`
should do the trick. I'll add this to the test and to the [function](https://github.com/creativesoftwarefdn/weaviate/blob/b10d139b2b97c85a832840bb625c6ae952cd7c6f/telemetry/reporting.go#L197) responsible for posting logs to the endpoint, I'll test if it still functions as expected afterwards.

**Comment by etiennedi** [comment]
@JeroenStravers1 can this be closed?

**Comment by JeroenStravers1** [comment]
Closing gh-829, telemetry no longer returns an EOF error
