### ISSUE TITLE
Editing schema property doesn't persist

### ISSUE THREAD

**Issue by dljcollette** [creativesoftwarefdn/weaviate#839]
When editing a schema property like `PUT http://localhost:8080/weaviate/v1/schema/things/Company/properties/description` with a body like:
```
{ cardinality: "atMostOne"
dataType: ["text"]
description: ""
keywords: []
name: "description" }
```
it will only persist changes in for `name`. I would expect it to persist the complete payload.

**Comment by etiennedi** [comment]
This is essentially the same as #832, closing this one and copying the OP over.
