### ISSUE TITLE
Can't delete property

### ISSUE THREAD

**Issue by dljcollette** [creativesoftwarefdn/weaviate#843]
After creating a property called `name` on `Animals` I fetch classes with `GET http://localhost:8080/weaviate/v1/meta` which returns `{ actionsSchema: { classes: [] }, hostname: "http://[::]:8080", thingsSchema: { classes: [{class: "Animals", description: "This is an animal description", keywords: [{keyword: "shops", weight: 1}], properties: [{cardinality: "atMostOne", dataType: ["string"], name: "name"}] }, type: "thing" }`

`DELETE http://localhost:8080/weaviate/v1/schema/things/Animals/properties/name` returns `500 Internal Server Error` with `message: "could not migrate database schema: could not get mapped name for property: property test for class name Animals is not mapped to a janus name"`

I would expect the `DELETE` request to succeed.

Please note this error does only happen on the properties that were create with the error mentioned in #842.

**Comment by etiennedi** [comment]
> Please note this error does only happen on the properties that were create with the error mentioned in #842.

Thanks, this is very valuable info. I'm starting to see a pattern. When we create a property the process consists of two processes that cannot be grouped into an atomic unit: Create the property in the database (in this case Janusgraph) schema and update our own representation of the schema (currently stored in the distributed Key-Value Store etcd). 

Based on this error at deletion it seems as if one of those succeeds, but the other one doesn't. Most likely this one will go away if we identified and fixed the issue in #842

**Comment by etiennedi** [comment]
Closing in favor of #846
