### ISSUE TITLE
Can't create thing

### ISSUE THREAD

**Issue by dljcollette** [creativesoftwarefdn/weaviate#844]
`POST http://localhost:8080/weaviate/v1/things` with body `{ class: "Animals", schema: {name: "Monkey"} }` doesn't return a response body nor code.

Previous to this steps and errors occurred as described in #842 and #843.

**Comment by etiennedi** [comment]
Ok, so here are two separate issues:

1. We have an inconsistent schema state as described in #842 and #843, that explains why it's not working
2. There must be some error handling missing, probably an internal `panic`, so we don't return any response

While technically independent from one another, we only run into 2 if the problem described in 1 occurs.

**Comment by etiennedi** [comment]
Closing in favor of #846
