### ISSUE TITLE
Weaviate should fail to add to schema when not in c11y

### ISSUE THREAD

**Issue by bobvanluijt** [creativesoftwarefdn/weaviate#855]
While running the latest Weaviate, I'm able to add concepts with words that are _not_ in the c11y.

Example:

```bash
curl -X POST http://localhost:8080/weaviate/v1/schema/things -H "Content-Type: application/json" -d '{
    "class": "Rliehjrglherglr", # <== THIS SHOULD FAIL
    "keywords": [{
        "keyword": "park",
        "weight": 0.01
    }, {
        "keyword": "animals",
        "weight": 0.01
    }],
    "description": "Animal park",
    "properties": [{
        "dataType": [
            "string"
        ],
        "cardinality": "atMostOne",
        "description": "Name of the Zoo",
        "name": "name",
        "keywords": [{
            "keyword": "identifier",
            "weight": 0.01
        }]
    }]
}'
```

**Comment by etiennedi** [comment]
@bobvanluijt I can only imagine you are on an old version, this should not be possible anymore after #851

**Comment by etiennedi** [comment]
Removing the Blocker label. We have identified over Slack that this seems to be based on a misunderstanding in the original implemenation of around 6 months back. It is implemented in a way that the class name doesn't have to be c11y-valild, if there are (valid) keywords present. This doesn't seem to reflect the desired behavior, so we still have a bug/issue, but enough to justify a blocker anymore.

**Comment by bobvanluijt** [comment]
Obsolete
